### ISSUE TITLE
Libvirt provisioning fails during linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml': line 376

### ISSUE THREAD

**Issue by mcornea** [CentOS-PaaS-SIG/linchpin#1023]
Libvirt provisioning fails during linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml': line 376:

TASK [libvirt : set_fact] ******************************************************
ok: [localhost] => (item=[0, 0]) => {"ansible_facts": {"macs": ["52:54:00:7c:20:fe"]}, "changed": false, "node": [0, 0]}
ok: [localhost] => (item=[0, 1]) => {"ansible_facts": {"macs": ["52:54:00:7c:20:fe", "52:54:00:25:87:47"]}, "changed": false, "node": [0, 1]}
ok: [localhost] => (item=[0, 2]) => {"ansible_facts": {"macs": ["52:54:00:7c:20:fe", "52:54:00:25:87:47", "52:54:00:72:c2:72"]}, "changed": false, "node": [0, 2]}
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 1\n\nThe error appears to have been in '/tmp/linchpin/.venv/lib/python2.7/site-packages/linchpin/provision/roles/libvirt/tasks/provision_libvirt_node.yml': line 376, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
	to retry, use: --limit @/tmp/linchpin/.venv/lib/python2.7/site-packages/linchpin/provision/libvirt.retry

PinFile:

```yaml
---
libvirt-network:
  topology:
    topology_name: "libvirt_network"
    resource_groups:
      - resource_group_name: baremetal_net
        resource_group_type: libvirt
        resource_definitions:
          - name: baremetal
            role: libvirt_network
            uri: qemu:///system
            forward_mode: nat
            ip: 192.168.123.1
            dhcp_start: 192.168.123.100
            dhcp_end: 192.168.123.150
            delete_on_destroy: yes
            domain: ostest.test.metalkube.org
            bridge: baremetal
            dns:
              services:
                - name: etcd-server-ssl
                  protocol: tcp
                  domain: ostest.test.metalkube.org
                  target: etcd-0.ostest.test.metalkube.org
                  port: 2380
                - name: etcd-server-ssl
                  protocol: tcp
                  domain: ostest.test.metalkube.org
                  target: etcd-1.ostest.test.metalkube.org
                  port: 2380
                - name: etcd-server-ssl
                  protocol: tcp
                  domain: ostest.test.metalkube.org
                  target: etcd-2.ostest.test.metalkube.org
                  port: 2380
              hosts:
                - ip: 192.168.123.5
                  hostnames:
                    - api
                - ip: 192.168.123.2
                  hostnames:
                    - dns

      - resource_group_name: provisioning_net
        resource_group_type: libvirt
        resource_definitions:
          - name: provisioning
            role: libvirt_network
            uri: qemu:///system
            bridge: provisioning
            delete_on_destroy: yes
cfgs:
  libvirt:
    __IP__: name
    __ADDRESS__: ip

libvirt-new:
  topology:
    topology_name: rhhi
    resource_groups:
      - resource_group_name: masters
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: master
            uri: qemu:///system
            count: 3
            image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
            memory: 16384
            vcpus: 4
            arch: x86_64
            ssh_key: id_rsa
            additional_storage: 42G
            name_separator: '-'
            networks:
              - name: baremetal
              - name: provisioning
                dhcp: no
            storage:
              - name: osd0
                size: 1
                units: G
                disk_type: virtio_blk
                device: vdb

      - resource_group_name: clients
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: client
            uri: qemu:///system
            count: 1
            image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
            memory: 16384
            vcpus: 4
            arch: x86_64
            additional_storage: 50G
            name_separator: '-'
            ssh_key: id_rsa
            networks:
              - name: baremetal
              - name: baremetal
              - name: provisioning
                dhcp: no

  layout:
    inventory_layout:
      vars:
        hostname: __IP__
        ansible_ssh_host: __ADDRESS__
        ansible_ssh_user: centos
        ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
      hosts:
        master:
          count: 3
          host_groups:
            - master
        client:
          host_groups:
            - client

  hooks:
    postdestroy:
      - name: vbmc cleanup
        type: ansible
        context: True
        actions:
          - playbook: vbmc.yaml
            extra_vars: { "action": "cleanup" }
    postup:
      - name: vms network update
        type: ansible
        context: True
        actions:
          - playbook: net_update.yaml
      - name: set up client ssh key
        type: ansible
        context: True
        actions:
          - playbook: client_ssh_key.yaml
      - name: vbmc configure
        type: ansible
        context: True
        actions:
          - playbook: vbmc.yaml
            extra_vars: { "action": "install" }
```
