### ISSUE TITLE
Error to generate inventory from layout with boolean variable

### ISSUE THREAD

**Issue by wainersm** [CentOS-PaaS-SIG/linchpin#1026]
Provision fails if It has in the inventory layout any variable with boolean value.

The inventory layout file I am using has an entry to "host_key_checking":

```
---
inventory_layout:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_user: root
    host_key_checking: False
  hosts:
    beaker_node:
      host_groups:
        - beaker_hosts
      count: 2
``` 

When executed linchpin up it fails with:
`Error: coercing to Unicode: need string or buffer, bool found`

It works fine if I remove the "host_key_checking" entry.
