### ISSUE TITLE
RFE: fetch remote hook urls when mentioned in Pinfile 

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#1059]
Currently, there is no provision to reference remote URLs as a source in Pinfile. 
With this feature, users should be able to reference accessible URLs inside a Pinfile. 

example:

Pinfile:
```yaml
os-server-addl-vols:
  topology:
    topology_name: os-server-inst
    resource_groups:
      - resource_group_name: os-server-addl-vols
        resource_group_type: openstack
        resource_definitions:
          - name: "test_keypairsk"
            role: os_keypair
        credentials:
          filename: clouds.yaml
          profile: ci-rhos
      - resource_group_name: os-server-addl-vols
        resource_group_type: openstack
        resource_definitions:
          - name: "database"
            role: os_server
            flavor: m1.small
            image: CentOS-7-x86_64-GenericCloud-1612
            count: 1
            keypair: testkeypair_sk
            fip_pool: 10.8.240.0
            networks:
              - e2e-openstack
        credentials:
          filename: clouds.yaml
          profile: ci-rhos
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        addl-vols-node:
          count: 1
          host_groups:
            - hello
  hooks:
    postup:
      - name: test
        type: ansible
        src: "<External github/http/url>"
        context: True
        actions:
          - playbook: ping.yaml
            extra_vars: 
              ansible_ssh_private_key_file: "/home/srallaba/workspace/lp_ws/ex_hooks/os_workspace/keys/testkeypair_sk.pem"
              ansible_ssh_user: centos
```
