### ISSUE TITLE
Fix hook communication

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1158]
**Is your feature request related to a problem? Please describe.**
Sort of.  The mechanism for hook communication is clunky

**Describe the solution you'd like**
Instead of passing data via stdio, I'd like to open a memory pipe and use ipc to allow the hooks to gather data about previous runs

**Comment by 14rcole** [comment]
I'd like to do this via a named pipe so that we don't have to include a growing number of arguments on the command line.  If we want to include data from previous runs of linchpin, the data we pass can get messy quite quickly.  Furthermore, not all hooks will need this data.  More importantly though, having hooks write data back via stderr is poor form.  This is roughly what I expect the code with the named pipe to look like

```python
pipe = os.mkfifo('/path/to/fifo')
# write relevant data to pipe
command = "" # add the path to the pipe to the end of the command
proc = subprocess.Popen(command, shell=True, stdout.subprocess.Pipe)

# at this point, data will be read by the hook, and subsequently written by the hook
proc.wait()
hook_data = pipe.read()
# at this point the hook data can be added to the rundb
```

Advantages of this implementation:

- simple
- Flexible
- Less is likely to go wrong than writing to stderr because we can guarantee that only data we want to be written will be written

Disadvantages:

- more work for the user
  - They have to read/write to a special structure
- The user MUST read from the pipe.  Otherwise linchpin will collect the data it wrote to the pipe and linclude that in the rundb
  - This can be avoided, but it's challenging.  Particularly if the user writes to the rundb but does not read

Another option is to open some sort of external process or network socket from which both processes can read and write. That way processes can read and write to something that controls the flow of data.  This of course may be over-engineering

A third option is to simply open two pipes - one for each direction (one read and one write). This allows data to flow all in the same direction but requires that more data be passed to the command line.

@samvarankashyap @abraverm @JunqiZhang0 what are your thoughts?

**Comment by samvarankashyap** [comment]
@14rcole I think I am missing something here.
When you say hook communication. I think each hook should be able to access variables passed to other hooks within Pinfile.
for example : 
```
---
os-server-addl-vols:
  topology:
    topology_name: os-server-inst
    resource_groups:
      - resource_group_name: os-server-addl-vols
        resource_group_type: openstack
        resource_definitions:
        - name: "database"
          role: os_server
          flavor: m1.small
          image: CentOS-7-x86_64-GenericCloud-1612
          count: 1
          keypair: testkeypair_sk
          fip_pool: 10.8.240.0
          networks:
          - e2e-openstack
        credentials:
          filename: clouds.yaml
          profile: ci-rhos
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        addl-vols-node:
          count: 1
          host_groups:
            - hello
  hooks:
    postup:
        actions:
        - name: osoos
          type: ansible
          context: True
          actions:
          - playbook: install_packages.yaml
            extra_vars:
              ansible_ssh_private_key_file: "testkeypair_sk.key"
              ansible_ssh_user: centos
              test_var1: test_value
          - playbook: git_clone.yaml
            extra_vars:
              ansible_ssh_private_key_file: "testkeypair_sk.key"
              ansible_ssh_user: centos
        - name: test_communication_hook
          type: ansible
          context: True
          actions:
          - playbook: playbook_displaying_facts_set_in_osos_hook.yaml
             # the above hook should be able to access the facts set by 
            extra_vars:
              ansible_ssh_private_key_file: "testkeypair_sk.key"
              ansible_ssh_user: centos
```
Are we on the same page? 
@14rcole Could you please explain breifly with example when you mean fixing hook communication . 
Thanks.
