### ISSUE TITLE
Local Python path used at remote libvirt location

### ISSUE THREAD

**Issue by goldmann** [CentOS-PaaS-SIG/linchpin#1228]
**Describe the bug**
When you use linchpin installed for example in a virtual environment it is impossible to connect to remote libvirt hosts.

```
TASK [libvirt : ensure local_image_path directory exists] ***********************************************************************************
fatal: [localhost -> REDACTED]: FAILED! => {"changed": false, "module_stderr": "Shared connection to REDACTED closed.\r\n", "module_stdout": "/bin/sh: /home/goldmann/.virtualenvs/linchpin/bin/python2: No such file or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}
```

This is related to this comment: https://github.com/CentOS-PaaS-SIG/linchpin/pull/586#issuecomment-388383512

**Comment by 14rcole** [comment]
Can you share the PinFile used to provision your machines?

**Comment by goldmann** [comment]
PinFile:

```yaml
dummy_cluster:
    topology: gluster-libvirt.yml
    layout: layout.yml
```

gluster-libvirt.yml:

```yaml
topology_name: gluster-libvirt
resource_groups:
  - resource_group_name: gluster-libvirt
    resource_group_type: libvirt
    resource_definitions:
      - role: libvirt_node
        remote_user: root
        name: gluster
        uri: qemu+ssh://root@REDACTED/system
        count: 1
        image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1905.qcow2.xz
        memory: 4096
        vcpus: 2
        arch: x86_64
        networks:
          - name: default
          - name: isolated
        additional_storage: 10G
```

layout.yml:

```yaml
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 1
      host_groups:
        - gluster
```
