### ISSUE TITLE
[openstack] Add option for os_server to specify device path for attached volumes

### ISSUE THREAD

**Issue by lukas-bednar** [CentOS-PaaS-SIG/linchpin#1245]
```
  os_server:
        volumes:
          - name: "{{ executor_name }}-local-storage-{{ workerid }}-vdb"
            dev_path: /dev/vdb
```

**Is your feature request related to a problem? Please describe.**
I want to have control over path to device which I am attaching to machine.

**Describe the solution you'd like**
The volume X, will get attached to VM as `/path/tomyvolume`

**Describe alternatives you've considered**
I am using custom ansible playbook to attach these volumes as a part of post provisioning.
