### ISSUE TITLE
Shell Hooks do not run on target machines with ansible 2.8

### ISSUE THREAD

**Issue by 14rcole** [CentOS-PaaS-SIG/linchpin#1263]
**Describe the bug**
Hooks do not run on target machines in linchpin with ansible>=2.8.  For some ansible uses localhost as the inventory and attempts to run all steps on the local machine

**To Reproduce**
1. Run a linchpin workspace with hooks

**Expected behavior**
Postup hooks are run on target machine

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue

**Additional context**
I discovered this because I was running Silverblue, which does not include yum or dnf.  It may be hard to troubleshoot on other machines

**Comment by samvarankashyap** [comment]
@14rcole do you have an example for it. 
Do you have context variable set to True? in hooks? 
hooks run on inventory only when the context variable is set to True
and host running linchpin has access provisioned inventory.

**Comment by 14rcole** [comment]
Context isn't set.  Is it true by default?  I was trying to provision the `openshift-on-openstack` example

**Comment by samvarankashyap** [comment]
@14rcole I don't think its True by default. 
Could you try adding context: True to hooks 
and try again.

**Comment by samvarankashyap** [comment]
@14rcole Please try out this example mentioned in linchpin docs 
https://linchpin.readthedocs.io/en/latest/hooks_examples.html
https://github.com/samvarankashyap/linchpin_hooks_openstack_ws

**Comment by 14rcole** [comment]
I was looking in the wrong place.  `context: True` is there and its still not working

**Comment by samvarankashyap** [comment]
@14rcole Was the example not working too? 
https://github.com/samvarankashyap/linchpin_hooks_openstack_ws

**Comment by samvarankashyap** [comment]
@14rcole Further is this only specific to ansible version 2.8 ??

**Comment by samvarankashyap** [comment]
@14rcole w.r.to example given in #1328 
It looks like the hooks are running on the target machine
when we pass the required parameters. 
Do you have an example where it does not work ??
Could you post it here?

**Comment by 14rcole** [comment]
I do, the openshift on openstack workspace
https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/docs/source/examples/workspaces/openshift-on-openstack/PinFile

**Comment by 14rcole** [comment]
@samvarankashyap Using this stripped-down version of one of the openstack examples:
```yaml
---
os-server-new:
  topology:
    topology_name: os-server-new
    resource_groups:
      - resource_group_name: os-server-new
        resource_group_type: openstack
        resource_definitions:
          - name: "ci-lp-cp-{{ distro | default('') }}frontend"
            role: os_server
            flavor: {{ flavor | default('m1.small') }}
            image: {{ image | default('CentOS-7-x86_64-GenericCloud-1808') }}
            count: 1
            keypair: {{ keypair | default('ci-factory') }}
            auto_ip: no
            networks:
              - {{ networks | default('provider_net_cci_6') }}
        {% if credentials is defined %}
        credentials:
          filename: {{ credentials.filename }}
          profile: {{ credentials.profile }}
        {% else %}
        credentials:
          filename: clouds.yaml
          profile: ci-rhos
        {% endif %}
  hooks:
    postup:
      - name: hostname
        type: shell
        context: True
        actions:
          - echo $(hostname)
      - name: whoami
        type: shell
        context: True
        actions:
          - echo $(whoami)
```

I get the following output from the hooks

```
running postup hooks
-------
start hook shell:hostname
rycole-f30-silverblue -- []

end hook shell:hostname
-------
-------
start hook shell:whoami
ryan -- [{"state":"postup","return_code":0}]

end hook shell:whoami
```

As you can see, these are running on my local machine
