### ISSUE TITLE
Can't destroy an AWS security group provisioned by linchpin

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1265]
**Describe the bug**
Provisioned an AWS security group. When I destroyed it everything from Linchpin side returned successful but when I look at the AWS EC2 dashboard the security group is still there. 

Looking at the aws role, I see no equivalent **teardown_aws_sg.yml**. Comparing it to the openstack role, where it can provision and teardown security groups there. 

**To Reproduce**
1. Create a pinfile
```
aws-sg-new:
  topology:
    topology_name: aws-sg-new
    resource_groups:
      - resource_group_name: "aws"
        resource_group_type: "aws"
        resource_definitions:
          - name: "aws_sg_test"
            role: "aws_sg"
            description: {{ description | default('aws ssh security group') }}
            region: "{{ region | default('us-east-1') }}"
            {% if rules is defined %}
            rules:
              {% for rule in rules %}
              - rule_type: {{ rule.type }}
                from_port: {{ rule.from_port }}
                to_port: {{ rule.to_port }}
                proto: {{ rule.proto }}
                cidr_ip: {{ rule.cidr_ip }}
              {% endfor %}
            {% else %}
            rules:
              - rule_type: "inbound"
                from_port: "8"
                to_port: -1
                proto: "icmp"
                cidr_ip: "0.0.0.0/0"
              - rule_type: "inbound"
                from_port: 22
                to_port: 22
                proto: "tcp"
                cidr_ip: "0.0.0.0/0"
              - rule_type: "outbound"
                from_port: 0
                to_port: 65535
                proto: "all"
                cidr_ip: "0.0.0.0/0"
            {% endif %}
        {% if credentials is defined %}
        credentials:
          filename: {{ credentials.filename }}
          profile: {{ credentials.profile }}
        {% else %}
        credentials:
          filename: aws.key
          profile: default
        {% endif %}
```
2. run ```linchpin up```
3. confirm the security group is created successfully in AWS EC2 console
4. run ```linchpin destroy```
5. check in the EC2 console again the security group is still there.  

**Expected behavior**
When running ```linchpin destroy``` Linchpin is successfully able to remove the security group resource that it provisioned.
