### ISSUE TITLE
linchpin libvirt provider leaves the VMs in 'shut off' state after linchpin up

### ISSUE THREAD

**Issue by mcornea** [CentOS-PaaS-SIG/linchpin#1315]
**Describe the bug**
linchpin libvirt provider leaves the VMs in 'shut off' state after linchpin up. Expected state is that the VMs are powered on:

```shell
(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# linchpin --template-data @hooks/ansible/rhhi-setup/extravars.yaml -v up --no-hooks libvirt-network libvirt-new

[...]

TASK [gather_resources : Add inventory_path to outputs] **************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "output": 6}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=73   changed=10   unreachable=0    failed=0    skipped=62   rescued=0    ignored=1   

Action 'up' on Target 'libvirt-new' is complete

ID: 6
Action: up

Target              	Run ID	uHash	Exit Code 
-------------------------------------------------
libvirt-network     	     6	a6d14c	        0
libvirt-new         	     6	cffa93	        0

(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# virsh list --all
 Id    Name                           State
----------------------------------------------------
 -     rhhi-node-master-0             shut off
 -     rhhi-node-master-1             shut off
 -     rhhi-node-master-2             shut off
 -     rhhi-node-worker-0             shut off

```

**To Reproduce**

```shell
(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# cat PinFile 
#jinja2:lstrip_blocks: True
---
libvirt-network:
  topology: libvirt-network.yml
  hooks:
    predestroy:
      - name: rhhi-setup
        type: ansible
        context: True
        actions:
          - playbook: requirements.yaml

cfgs:
  libvirt:
    __IP__: name
    __ADDRESS__: ip

libvirt-new:
  topology: libvirt-new.yml
  layout: libvirt-new.yml
  hooks:
    postdestroy:
      - name: rhhi-setup
        type: ansible
        context: True
        actions:
          - playbook: vbmc.yaml
            extra_vars: { "action": "cleanup" }
    postup:
      - name: rhhi-setup
        type: ansible
        context: True
        actions:
          - playbook: dns_update.yaml
            vars: extravars.yaml
          - playbook: nic_adjust.yaml
            vars: extravars.yaml
          - playbook: vbmc.yaml
            extra_vars: { "action": "install" }

beaker-specific-host:
  topology: beaker-specific-host.yml
  layout: beaker-layout.yml

beaker-qe-dedicated:
  topology: beaker-qe-dedicated.yml
  layout: beaker-layout.yml

beaker-ci-pool:
  topology: beaker-ci-pool.yml
  layout: beaker-layout.yml

openstack-target:
  topology: openstack-topology.yml
  layout: openstack-layout.yml


(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# cat topologies/libvirt-new.yml
---
topology_name: rhhi
resource_groups:
  - resource_group_name: rhhi-node-master
    resource_group_type: libvirt
    resource_definitions:
      - role: libvirt_node
        name: rhhi-node-master
        uri: qemu:///system
        count: 3
        image_src: http://$URL/rhel-guest-image-8.0-1876.x86_64.qcow2
        cpu_mode: host-passthrough
        memory: {{ node_memory }}
        vcpus: {{ node_vcpus }}
        arch: x86_64
        ssh_key: id_rsa
        additional_storage: 42G
        disk_type: virtio_scsi
        name_separator: '-'
        networks:
          - name: baremetal
          - name: provisioning
            dhcp: false
        storage:
          - name: osd0
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdb
          - name: osd1
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdc
          - name: osd2
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdd
          - name: osd3
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sde
  - resource_group_name: rhhi-node-worker
    resource_group_type: libvirt
    resource_definitions:
      - role: libvirt_node
        name: rhhi-node-worker
        uri: qemu:///system
        count: {{ node_count|int - 3 }} # If this results in count <= 0, I am quite sure linchpin up will fail
        memory: {{ node_memory }}
        vcpus: {{ node_vcpus }}
        image_src: http://$URL/rhel-guest-image-8.0-1854.x86_64.qcow2
        cpu_mode: host-passthrough
        arch: x86_64
        ssh_key: id_rsa
        additional_storage: 42G
        disk_type: virtio_scsi
        name_separator: '-'
        networks:
          - name: baremetal
          - name: provisioning
            dhcp: false
        storage:
          - name: osd0
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdb
          - name: osd1
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdc
          - name: osd2
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sdd
          - name: osd3
            size: {{ osd_disk_size }}
            cache: unsafe
            units: G
            disk_type: virtio_scsi
            device: sde


(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# cat topologies/libvirt-network.yml 
---
topology_name: "libvirt_network"
resource_groups:
  - resource_group_name: baremetal_net
    resource_group_type: libvirt
    resource_definitions:
      - name: baremetal
        role: libvirt_network
        uri: qemu:///system
        forward_mode: nat
        ip: 192.168.123.1
        dhcp_start: 192.168.123.100
        dhcp_end: 192.168.123.150
        delete_on_destroy: yes
        domain: {{ cluster_domain }}
        bridge: baremetal
        dns:
          forwarders:
            - domain: apps.{{ cluster_domain }}
              addr: 127.0.0.1
          hosts:
            - ip: 192.168.123.5
              hostnames:
                - api

  - resource_group_name: provisioning_net
    resource_group_type: libvirt
    resource_definitions:
      - name: provisioning
        role: libvirt_network
        uri: qemu:///system
        bridge: provisioning
        delete_on_destroy: yes


(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# cat layouts/libvirt-new.yml 
---
inventory_layout:
  vars:
    hostname: __IP__
    ansible_ssh_host: __ADDRESS__
    ansible_ssh_user: {{ provisionhost_user }}
    ansible_python_interpreter: '/usr/libexec/platform-python'
    ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
  hosts:
    master:
      count: 3
      host_groups:
        - master
        - openshift
    worker:
      count: {{ node_count|int - 3 }}
      host_groups:
        - worker
        - openshift
    openshift:
      count: {{ node_count }}
      host_groups:
        - openshift

(rhhi-qe-venv) [root@sealusa2 linchpin_workspace]# linchpin --template-data @hooks/ansible/rhhi-setup/extravars.yaml -v up --no-hooks libvirt-network libvirt-new

**Additional context**

This behavior changed in linchpin version 1.8.1 it works fine in 1.7.6.2

**Comment by samvarankashyap** [comment]
@JunqiZhang0 @14rcole : 
here is another simpler example that does not work:

```
---
libvirt-network:
  topology:
    topology_name: "libvirt_network"
    resource_groups:
    - resource_group_name: baremetal_net
      resource_group_type: libvirt
      resource_definitions:
      - name: baremetal
        role: libvirt_network
        uri: qemu:///system
        forward_mode: nat
        ip: 192.168.123.1
        dhcp_start: 192.168.123.100
        dhcp_end: 192.168.123.150
        delete_on_destroy: yes
        domain: {{ cluster_domain| default('test') }}
        bridge: baremetal
        dns:
          forwarders:
            - domain: apps.{{ cluster_domain | default('test') }}
              addr: 127.0.0.1
          hosts:
            - ip: 192.168.123.5
              hostnames:
                - api
    - resource_group_name: provisioning_net
      resource_group_type: libvirt
      resource_definitions:
      - name: provisioning
        role: libvirt_network
        uri: qemu:///system
        bridge: provisioning
        delete_on_destroy: yes

libvirt-new:
  topology:
    topology_name: libvirt-new
    resource_groups:
      - resource_group_name: libvirt-new
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: centosnom
            uri: {{ uri | default('qemu:///system') }}
            count: 3
            image_src: {{ image_src | default('http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz') }}
            memory: {{ memory | default('2048') }}
            vcpus: {{ vcpus | default('1') }}
            arch: {{ arch |  default('x86_64') }}
            ssh_key: {{ ssh_key | default('libvirt') }}
            networks:
            - name: baremetal
            - name: provisioning
              dhcp: false
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        example-node:
          count: 1
          host_groups:
            - example

```
