### ISSUE TITLE
[libvirt] Can't acquire ip address after provisioning

### ISSUE THREAD

**Issue by JunqiZhang0** [CentOS-PaaS-SIG/linchpin#1335]
**Describe the bug**
The libvirt provision will get stuck on mac_ip acquisition stage and failed without any ip assigned

**PinFile**
```
libvirt-multi-node-net:
  topology:
    topology_name: libvirt-multi-node-net
    resource_groups:
      - resource_group_name: "Test-Net"
        resource_group_type: "libvirt"
        resource_definitions:
          - name: static-DHCP-Test
            role: libvirt_network
            uri: {{ uri | default('qemu:///system') }}
            ip: {{ ip | default('192.168.74.100') }}
            dhcp_start: {{ dhcp_start | default('192.168.74.101') }}
            forward_mode: {{ forward_mode | default('nat') }}
            dhcp_end: {{ dhcp_end | default('192.168.74.112') }}
            domain: {{ domain | default('linchpin.net') }}
            netmask: {{ netmask | default('255.255.255.0') }}
            delete_on_destroy: {{ delete | default('True') }}

libvirt-new:
  topology:
    topology_name: libvirt-new
    resource_groups:
      - resource_group_name: libvirt-new
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: centosnom
            uri: {{ uri | default('qemu:///system') }}
            count: 3
            image_src: {{ image_src | default('http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz') }}
            memory: {{ memory | default('2048') }}
            vcpus: {{ vcpus | default('1') }}
            arch: {{ arch |  default('x86_64') }}
            ssh_key: {{ ssh_key | default('libvirt') }}
            networks:
            - name: default
            - name: static-DHCP-Test
              dhcp: false
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        example-node:
          count: 1
          host_groups:
            - example
```

**Expected behavior**
Successful provision

**Software version**
ansible 2.8.4 + python 2.7.16 + linchpin (develop)

**possible solution**
This commit caused this bug : b349a95c542aa3d2b3dd58ee0e2f978f970efbb1
Could revert it, but I think there might be other problem could cause this bug.
