### ISSUE TITLE
linchpin -v up exits with Error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mcornea** [CentOS-PaaS-SIG/linchpin#1477]
linchpin -v up exits with:
```
Action 'up' on Target 'libvirt-new' is complete
Error: [Errno 2] No such file or directory
```
and there's no inventory file in the inventory directory

To reproduce use the following Pinfile. Tested against commit bc74b15ce970f8ca1ff0852ac156d3f931a4ee0e

```
#jinja2:lstrip_blocks: True
---
libvirt-network:
  topology:
    topology_name: "libvirt_network"
    resource_groups:
      - resource_group_name: baremetal_net
        resource_group_type: libvirt
        resource_definitions:
          - name: baremetal
            role: libvirt_network
            uri: qemu:///system
            forward_mode: nat
            ip: 192.168.123.1
            dhcp_start: 192.168.123.100
            dhcp_end: 192.168.123.150
            delete_on_destroy: yes
            domain: ostest.test.metalkube.org
            bridge: baremetal
            dns:
              forwarders:
                - domain: apps.ostest.test.metalkube.org
                  addr: 127.0.0.1
              hosts:
                - ip: 192.168.123.5
                  hostnames:
                    - api
    
      - resource_group_name: provisioning_net
        resource_group_type: libvirt
        resource_definitions:
          - name: provisioning
            role: libvirt_network
            uri: qemu:///system
            bridge: provisioning
            delete_on_destroy: yes

cfgs:
  libvirt:
    __IP__: name
    __ADDRESS__: ip

libvirt-new:
  topology:
    topology_name: ocp-edge
    resource_groups:
      - resource_group_name: ocp-edge-master
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: master
            uri: qemu:///system
            count: 1
            image_src: http://url/rhel-guest-image-8.0-1876.x86_64.qcow2
            cpu_mode: host-passthrough
            memory: 4096
            vcpus: 2
            arch: x86_64
            ssh_key: id_rsa
            additional_storage: 42G
            disk_type: virtio_scsi
            name_separator: '-'
            cloud_config:
              users:
                - name: kni
                  gecos: Admin User
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  lock_passwd: false
            networks:
              - name: baremetal
              - name: provisioning
                dhcp: false

  layout:
    inventory_layout:
      vars:
        hostname: __IP__
        ansible_ssh_host: __ADDRESS__
        ansible_ssh_user: kni
        ansible_python_interpreter: '/usr/libexec/platform-python'
        ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
      hosts:
        master:
          count: 1
          host_groups:
            - master
            - openshift
        openshift:
          count: 1
          host_groups:
            - openshift
```
