### ISSUE TITLE
Wrap IPv6 addresses

### ISSUE THREAD

**Issue by yprokule** [CentOS-PaaS-SIG/linchpin#1691]
**Is your feature request related to a problem? Please describe.**

Accessing remote vm via its IPv6 address by    `ProxyCommand` fails like:

```yaml
node1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: kex_exchange_identification: Connection closed by remote host",
    "unreachable": true
}
```

Generated inventory looks like

```yaml
node1 hostname=node1 ansible_ssh_host=fd2e:1111:2222:3333::4444 ansible_ssh_user=admin ansible_python_interpreter=/usr/libexec/platform-python ansible_ssh_common_args=" -o stricthostkeychecking=no -o proxycommand='ssh -W %h:%p remote@host.example.com' "
```

After manually adjusting inventory and putting square `[` `]` brackets around IPv6 address eliminates the issue.

**Describe the solution you'd like**
Would be great to have IPv6 address in the inventory wrapped in square brackets, for e.g.:

`ansible_ssh_host=[fd2e:1111:2222:3333::4444]`
