### ISSUE TITLE
Failed to provision openstack port with os_port due to missing network param

### ISSUE THREAD

**Issue by Dannyb48** [CentOS-PaaS-SIG/linchpin#1739]
**Describe the bug**
Trying to provision a port on an openstack network using the os_port module fails with an error like

"Network is required"

I get the error even though I do specify name:

```
resource_group_type: openstack
resource_definitions:
   - role: os_port
     network: test_private_network
credentials:
  filename: clouds.yaml
  profile: openstack
```
According to ansible os_port module doc network name is required but linchpin is not setting that parameter.

**To Reproduce**
1. Define a pinfil with a resource_definition for role os_port
2. run linchpin -vvvv up
3. See error

**Expected behavior**
A port on an openstack network is successfully provisioned.
