### ISSUE TITLE
[OpenStack] Additional Volumes should be cleaned when I hit linchpin destroy

### ISSUE THREAD

**Issue by lyfofvipin** [CentOS-PaaS-SIG/linchpin#1754]
**Describe the bug**
I am trying to provision an OpenStack Server from a volume so if I pass volume name as image parameter it works but it creates an additional Volume and didn't clean that when I hit `linchpin destroy`.

**To Reproduce**
1. Create a Virtual environment ( Python 2.7 )
2. Install Linchpin
3. Provision an Openstack Server (From a Volume or Snapshot )
4. Hit linchpin destroy and you will see that additional isn't cleaned by it

PinFile:

```
simple:
  topology:
    topology_name: simple
    resource_groups:
      - resource_group_name: os_simple
        resource_group_type: openstack
        resource_definitions:
          - name: "RHEL8"
            role: os_server
            flavor: m1.medium
            keypair: el8build
            count: 1
            image: build_rpm_rhel-8.0
           boot_from_volume: true
            networks:
              - provider_net_quicklab
            availability_zone: nova
        credentials:
          filename: playbooks/clouds.yaml
          profile: openstack
```
NOTE: If I do not use boot_from_volume option then also it does not delete the additional volume.

**Expected behavior**
When I hit `linchpin destroy` It should clean all resources is created.

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux
 - Version: 7.7
- Linchpin Version : 2.0.3
