### ISSUE TITLE
1.0 error with linchpin init/linchpin up

### ISSUE THREAD

**Issue by dustymabe** [CentOS-PaaS-SIG/linchpin#264]
I tried `linchpin init` and `linchpin up` with 1.0.0 from pip and I see this error:

```
[root@n52 lp2]# linchpin init
PinFile and file structure created at /root/lp2
[root@n52 lp2]# linchpin up
        to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry
Target 'example_target': TASK: common : filtering the output for openshift v3 failed with error 'Unexpected failure during module execution.'
```

```
[root@n52 lp2]# linchpin --version
linchpin version 1.0.0
```

Note I did not use virtualenv, just pip directly.

**Comment by samvarankashyap** [comment]
@herlo its because of following code snippet in provision/roles/common/tasks/main.yml +101
```yaml
- name: "filtering the output for openshift v3"
  set_fact:
    openshift_res_grps: "{{ outputs.resource_groups | selectattr('res_group_type', 'equalto', 'openshift') | list }}"
  when: v3_schema_valid

- name: "filtering the output for openshift v4"
  set_fact:
    openshift_res_grps: "{{ outputs.resource_groups | selectattr('resource_group_type', 'equalto', 'openshift') | list }}"
  when: not v3_schema_valid
```

I wonder why this error is raised only when used with libvirt , When ran by provisioning duffy nodes it works fine . 
I added ignore_errors: yes to both of the tasks and provision ran into another issue 
```
lxml module not found
```
later i realised i have to install , libvirt extra dependencies too by 
```
pip install linchpin[libvirt]
```

later i ran into following issue while defining the node . 
```
TASK [libvirt : define node] ***************************************************
failed: [localhost] (item=[u'ex', {u'count': 1, u'res_type': u'libvirt_node', u'uri': u'qemu:///system', u'networks': [{u'name': u'linchpin-centos71'}], u'res_name': u'centos71', u'vcpus': 1, u'memory': 1024, u'arch': u'x86_64', u'image_src': u'http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz'}, 0, u'/var/lib/libvirt/images/linchpin/', u'qcow2']) => {"definition": ["ex", {"arch": "x86_64", "count": 1, "image_src": "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz", "memory": 1024, "networks": [{"name": "linchpin-centos71"}], "res_name": "centos71", "res_type": "libvirt_node", "uri": "qemu:///system", "vcpus": 1}, 0, "/var/lib/libvirt/images/linchpin/", "qcow2"], "failed": true, "msg": "Cannot check QEMU binary /usr/bin/qemu-kvm: No such file or directory"}
        to retry, use: --limit @/usr/lib/python2.7/site-packages/linchpin/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=35   changed=1    unreachable=0    failed=1   
```
@herlo any clue what is happening above ??
