### ISSUE TITLE
Authorization failing with linchpin 1.0.0

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#274]
Getting the following error when invoking linchpin with clouds.yaml living in the current folder;

linchpin -v up (I also tried linchpin -v --creds-path clouds.yaml up)
.
.
.
TASK [openstack : set cred profile] ********************************************
ok: [localhost]

TASK [openstack : Get creds from auth driver] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: Credential not found"}
...ignoring

TASK [openstack : set auth_var] ************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'output'\n\nThe error appears to have been in '/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_resource_group.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"set auth_var \"\n  ^ here\n"}
...ignoring

TASK [openstack : provisioning resource definitions of current group] **********
included: /home/vagrant/projects/linch-venv/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_res_defs.yml for localhost

TASK [openstack : provision resources of type os_server] ***********************
included: /home/vagrant/projects/linch-venv/lib/python2.7/site-packages/linchpin/provision/roles/openstack/tasks/provision_os_server.yml for localhost

TASK [openstack : provision/deprovision os_server resources by looping on count] ***
skipping: [localhost]

TASK [openstack : provision/deprovision os_server resources by looping on count] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_sOHvme/ansible_module_os_server2.py\", line 764, in <module>\n    main()\n  File \"/tmp/ansible_sOHvme/ansible_module_os_server2.py\", line 744, in main\n    cloud = shade.openstack_cloud(**cloud_params)\n  File \"/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/shade/__init__.py\", line 102, in openstack_cloud\n    cloud_config = config.get_one_cloud(**kwargs)\n  File \"/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/os_client_config/config.py\", line 1071, in get_one_cloud\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 162, in load_from_options\n    raise exceptions.MissingRequiredOptions(missing_required)\nkeystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url\n", "module_stdout": "", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/linchpin/provision/site.retry

=========================================

topology file:
```
---
topology_name: "cinch"
site: CSS
resource_groups:
  -
    resource_group_name: "CSS-testgroup"
    resource_group_type: "openstack"
    resource_definitions:
      - name: resource
        type: os_server
        flavor: m1.small
        image: rhel-7.2-server-x86_64-released
        count: 1
        keypair: css-central
        networks:
          - "CSS"
        fip_pool: "10.8.172.0/22"
    credentials:
      name: "CSS"
      profile: "CSS"
```

clouds.yaml file:
```
clouds:
  CSS:
    auth:
      auth_url: "http://dashboard.centralci.eng.rdu2.redhat.com:5000/v2.0"
      project_name: "CSS"
      username: <redacted>
      password: <redacted>
  CSS_TEST:
    auth:
      auth_url: "http://dashboard.centralci.eng.rdu2.redhat.com:5000/v2.0"
      project_name: "CSS-test"
      username: <redacted>
      password: <redacted>
```
