### ISSUE TITLE
linchpin 1.0.0 unable to provision beaker resource

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#276]
Starting with a fresh install, new virtualenv and fresh install of linchpin directly from the latest repo.

Running the linchpin -v up command results in the following;
```
TASK [rackspace : Initiating  Provisioning/Deprovioning of resources rackspace resource group] ***

TASK [beaker : allocate beaker outputs] ****************************************
ok: [localhost]

TASK [beaker : debug] **********************************************************
ok: [localhost] => {
    "bkr_res_grps": [
        {
            "job_group": "CS&S", 
            "recipesets": [
                {
                    "arch": "x86_64", 
                    "count": 1, 
                    "distro": "RHEL-7.3", 
                    "hostrequire": [
                        "arch=X86_64"
                    ], 
                    "keyvalue": [
                        "MEMORY>1000", 
                        "DISKSPACE>500"
                    ]
                }
            ], 
            "res_group_type": "beaker", 
            "resource_group_name": "pod_node1"
        }, 
        {
            "job_group": "CS&S", 
            "recipesets": [
                {
                    "arch": "x86_64", 
                    "count": 1, 
                    "distro": "RHEL-7.3", 
                    "hostrequire": [
                        "arch=X86_64"
                    ], 
                    "keyvalue": [
                        "MEMORY>1000", 
                        "DISKSPACE>500"
                    ]
                }
            ], 
            "res_group_type": "beaker", 
            "resource_group_name": "pod_node2"
        }, 
        {
            "job_group": "CS&S", 
            "recipesets": [
                {
                    "arch": "x86_64", 
                    "count": 1, 
                    "distro": "RHEL-7.3", 
                    "hostrequire": [
                        "arch=X86_64"
                    ], 
                    "keyvalue": [
                        "MEMORY>1000", 
                        "DISKSPACE>500"
                    ]
                }
            ], 
            "res_group_type": "beaker", 
            "resource_group_name": "pod_node3"
        }
    ]
}

TASK [beaker : provision beaker systems] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named bkr.client.task_watcher
failed: [localhost] (item={u'resource_group_name': u'pod_node1', u'res_group_type': u'beaker', u'job_group': u'CS&S', u'recipesets': [{u'count': 1, u'keyvalue': [u'MEMORY>1000', u'DISKSPACE>500'], u'hostrequire': [u'arch=X86_64'], u'arch': u'x86_64', u'distro': u'RHEL-7.3'}]}) => {"failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_8dF8RU/ansible_module_bkr_server.py\", line 10, in <module>\n    from bkr.client.task_watcher import watch_tasks\nImportError: No module named bkr.client.task_watcher\n", "module_stdout": "", "msg": "MODULE FAILURE", "res": {"job_group": "CS&S", "recipesets": [{"arch": "x86_64", "count": 1, "distro": "RHEL-7.3", "hostrequire": ["arch=X86_64"], "keyvalue": ["MEMORY>1000", "DISKSPACE>500"]}], "res_group_type": "beaker", "resource_group_name": "pod_node1"}}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named bkr.client.task_watcher
failed: [localhost] (item={u'resource_group_name': u'pod_node2', u'res_group_type': u'beaker', u'job_group': u'CS&S', u'recipesets': [{u'count': 1, u'keyvalue': [u'MEMORY>1000', u'DISKSPACE>500'], u'hostrequire': [u'arch=X86_64'], u'arch': u'x86_64', u'distro': u'RHEL-7.3'}]}) => {"failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bknm90/ansible_module_bkr_server.py\", line 10, in <module>\n    from bkr.client.task_watcher import watch_tasks\nImportError: No module named bkr.client.task_watcher\n", "module_stdout": "", "msg": "MODULE FAILURE", "res": {"job_group": "CS&S", "recipesets": [{"arch": "x86_64", "count": 1, "distro": "RHEL-7.3", "hostrequire": ["arch=X86_64"], "keyvalue": ["MEMORY>1000", "DISKSPACE>500"]}], "res_group_type": "beaker", "resource_group_name": "pod_node2"}}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named bkr.client.task_watcher
failed: [localhost] (item={u'resource_group_name': u'pod_node3', u'res_group_type': u'beaker', u'job_group': u'CS&S', u'recipesets': [{u'count': 1, u'keyvalue': [u'MEMORY>1000', u'DISKSPACE>500'], u'hostrequire': [u'arch=X86_64'], u'arch': u'x86_64', u'distro': u'RHEL-7.3'}]}) => {"failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_YCYr9o/ansible_module_bkr_server.py\", line 10, in <module>\n    from bkr.client.task_watcher import watch_tasks\nImportError: No module named bkr.client.task_watcher\n", "module_stdout": "", "msg": "MODULE FAILURE", "res": {"job_group": "CS&S", "recipesets": [{"arch": "x86_64", "count": 1, "distro": "RHEL-7.3", "hostrequire": ["arch=X86_64"], "keyvalue": ["MEMORY>1000", "DISKSPACE>500"]}], "res_group_type": "beaker", "resource_group_name": "pod_node3"}}
	to retry, use: --limit @/home/vagrant/projects/linch-venv/lib/python2.7/site-packages/linchpin/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1   
```

My PinFile:
```
#The following example illustrates the linchpinfile , ie., lpf
#SYNTAX:
#component_name:
#    topology_name: <string>  # refers to the name topology file either in package or local topologies folder
#    inventory_layout: <string> # refers to name of the inventory layout in package or local layouts folder
#on linchpin rise ,  the folder structure is created as follows
# component_name:
# ---- outputs
# ---- keystore
# ---- inventory

cinch:
  topology: beaker_server.yml
  layout: beaker_layout.yml
```

My topology file: (Structure copied directly from the examples folder on github)
```
---
topology_name: beaker_server
resource_groups:
  - resource_group_name: pod_node1
    res_group_type: beaker
    job_group: CS&S
    recipesets:
      - distro: RHEL-7.3
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>500
        hostrequire:
          - arch=X86_64
        count: 1
  - resource_group_name: pod_node2
    res_group_type: beaker
    job_group: CS&S
    recipesets:
      - distro: RHEL-7.3
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>500
        hostrequire:
          - arch=X86_64
        count: 1
  - resource_group_name: pod_node3
    res_group_type: beaker
    job_group: CS&S
    recipesets:
      - distro: RHEL-7.3
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>500
        hostrequire:
          - arch=X86_64
        count: 1
```

**Comment by seandst** [comment]
"hostrequire" is gone in 1.0, replaced with "hostrequires" and more flexible compatibility with the beaker API:
http://linchpin.readthedocs.io/en/develop/topologies_beaker.html#requiring-specific-hosts

Is there an outdated example that needs to be updated?

**Comment by danalanerh** [comment]
I see where I missed the s in the example. Still getting the same failure though;

Exceprted from the log: 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named bkr.client.task_watcher

Is there something else that needs to get installed other than the standard linchpin?

**Comment by danalanerh** [comment]
Also, is there a list of tags available in the hostrequires field?

**Comment by seandst** [comment]
Yeah, you'll need `beaker-client`, which should pull in the rest of its dependencies when installed. I believe that's the name of fedora package, as well as the pip package, but I'm not  100% sure.

I haven't found a list of tags available with the hostrequires field, but would definitely love one.

The new syntax, using "arch" as an example, would look like
```yaml
hostrequires
  - tag: arch
    op: "="
    value: "x86_64
```

I haven't yet found a list of tags that you can use in hostRequires, and it appears to be different than the ones you can use in the "keyvalue" block (they line up with the keys listed at https://beakerhost/view/systemhostname#essentials); the best reference that I have found is looking for "hostRequires" in this beaker doc: https://beaker-project.org/docs/user-guide/job-xml.html

The hostRequires tag in the job XML is almost frustratingly flexible, but the linchpin topology  representation of it should hopefully be able to keep up. For example, this tag:
```xml
<device op="=" type="network" vendor_id="8086" />
```
would look like this in a topology:
```yaml
hostrequires:
  - tag: device
    op: "="
    type: network
    vendor_id: "8086"
```

In general, the process of finding valid hostrequires tags for me has been a naive process of looking at the XML of existing jobs in beaker and using those as examples.
