### ISSUE TITLE
Attempting to use the preup and postdestroy hooks with type shell return an error

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#293]
PinFile:
```
#The following example illustrates the linchpinfile , ie., lpf
#SYNTAX:
#component_name:
#    topology_name: <string>  # refers to the name topology file either in package or local topologies folder
#    inventory_layout: <string> # refers to name of the inventory layout in package or local layouts folder
#on linchpin rise ,  the folder structure is created as follows
# component_name:
# ---- outputs
# ---- keystore
# ---- inventory

cinch:
  topology: cinch.yml
  layout: cinch.yml
  hooks:
    preup:
      - name: Pre Provision Actions
        type: shell
        actions:
          - echo "This is where I could do something prior to provisioning"
    postup:
      - name: Get System Info
        type: ansible
        path: "./ansible/playbooks/"
        actions:
          - playbook: test.yml
    postdestroy:
      - name: Post Destroy Actions
        type: shell
        actions:
          - echo "This is where I could do something just after returning our provisioned resources"
```
The output I get from both the preup and postdestroy is:
```
running preup hooks
start hook shell:Pre Provision Actions
----------

/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `echo "This is where I could do something prior to provisioning" schemas_folder=schemas  default_credentials_path={{ lookup('env', 'PWD') }}/credentials  schema_v4={{ lp_path }}/defaults/schemas/schema_v4.json  schema_v3={{ lp_path }}/defaults/schemas/schema_v3.json  hooks_folder=hooks  from_api=True  topologies_folder=topologies  lp_path=/home/vagrant/cinch-venv/lib/python2.7/site-packages/linchpin  pkg=linchpin  default_schemas_path={{ lp_path }}/defaults/schemas  resources_folder=resources  state=present  default_resources_path=/home/vagrant/projects/CI/CSS-145/CSS/resources  layout_file=/home/vagrant/projects/CI/CSS-145/CSS/layouts/cinch.yml  inventory_file=/home/vagrant/projects/CI/CSS-145/CSS/inventories/cinch.inventory  async_timeout=1000  check_mode=False  layouts_folder=layouts  inventories_folder=inventories  async=False  topology=/home/vagrant/projects/CI/CSS-145/CSS/topologies/cinch.yml  topology_name=cinch  inventory_dir=/home/vagrant/projects/CI/CSS-145/CSS/inventories  default_topologies_path={{ lp_path }}/defaults/topologies  default_layouts_path={{ lp_path }}/defaults/layouts  resource_file=/home/vagrant/projects/CI/CSS-145/CSS/resources/cinch.output  playbooks_folder=provision  default_inventories_path=/home/vagrant/projects/CI/CSS-145/CSS/inventories  output=True '
----------

end hook shell:Pre Provision Actions
```

I'm following the example list here:
https://github.com/samvarankashyap/linchtest/blob/master/PinFile
