### ISSUE TITLE
Creating two OpenStack hosts fails

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#335]
I'm trying to spin up two OpenStack hosts from the same topology which looks as follows:

```
---
topology_name: rhel7_rhel7_nosec_nossl
site: openstack
resource_groups:
  - resource_group_name: rhel7_rhel7
    res_group_type: openstack
    credentials:
      filename: clouds.yml
      profile: osp10
    res_defs:
      - res_name: nosec_nossl
        flavor: m1.medium
        res_type: os_server
        image: my-rhel-image
        count: 2
        keypair: ci-ops-central
        networks:
          - my_network
        fip_pool: 10.1.1.0
```

The only difference between this and a topology that works for me is ``count: 2`` instead of ``count: 1``.
