### ISSUE TITLE
Beaker Provisionging: Support provisioning different distro in single topology file 

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#341]
In the current beaker provisioning i see that you could provision single distro , i would like if the lichpin could support provisioning different distros (RHEL6.5, RHEL6.7) in a single topology, 

Example:
```
---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: your-beaker-group
    whiteboard: Arbitrary Job whiteboard string
    recipesets:
      - distro: RHEL-6.5
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
      - distro: RHEL-7.3
        arch: x86_64 
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
```
May be also if possible to support multiple archs,  We have certain beakerlib tests where in a single test suite requires multiple hosts (RHEL7 as Server and RHEL6 as client, Or RHEL7.3 as IPA server and RHEL7.4 as IPA client . or RHEL7.3 Server on s390 with RHEL7.4 client ).

Example:
```
---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: your-beaker-group
    whiteboard: Arbitrary Job whiteboard string
    recipesets:
      - distro: RHEL-6.5
        arch: s390
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
      - distro: RHEL-7.3
        arch: x86_64 
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
```

**Comment by herlo** [comment]
@mrniranjan Could you put them in different resource groups? Maybe like this?

```
---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: your-beaker-group
    whiteboard: Arbitrary Job whiteboard string
    recipesets:
      - distro: RHEL-6.5
        arch: s390
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
  - resource_group_name: test2
    res_group_type: beaker
    job_group: your-beaker-group
    whiteboard: Arbitrary Job whiteboard 2
    recipesets:
      - distro: RHEL-6.5
        arch: s390
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequires:
          - tag: processors
            op: ">="
            value: 4
          - tag: device
            op: "="
            type: "network"
        count: 1
```
Not sure if it will work as I'm not the beaker expert here. @greg-hellings ?
