### ISSUE TITLE
LinchPin 1.0.3 gives invalid syntax when provisioning beaker system (regression from 1.0.2)

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#356]
### Overview
I upgraded to LinchPin 1.0.3 from the 1.0.2 release available via pip. Since upgrading, I have not been able to provision systems from beaker due to a "syntax error". To confirm that this was indeed a regression, I reinstalled 1.0.2 on my system and the provisioning worked as expected. Digging further, installing LinchPin from source did not fix the issue. The error remains 'Unexpected failure during module execution'.

##### Versions Affected
Version 1.0.3 to Present

##### Topology
```
---
topology_name: cinch
resource_groups:
  - 
    resource_group_name: cinch-group
    resource_group_type: beaker
    whiteboard: Cinch Slave for testing Multi-Arch AOS
    recipesets:
      - distro: "RHEL-7.3"
        arch: ppc64le 
        variant: Server
        count: 1
        hostrequires:
          - tag: hostname
            op: "="
            value: "ibm-p8-storage-03.khw.lab.eng.bos.redhat.com"
```

##### Layout
```
---
inventory_layout:
  hosts:
    cinch-group:
      count: 1
      host_groups:
        - rhel7
        - certificate_authority
        - repositories
        - jenkins_slave
```
##### Variables
```
ansible_user: root
ansible_private_key_file: "~/.ssh/id_rsa"
ansible_connection: ssh
```

### Error Message
```
TASK [beaker : provision beaker systems] *****************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: invalid syntax
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

### Discovered Problem
It turns out that parentheses were added around an assignment in order to satisfy the style guide. However, this resulted in invalid syntax.
