### ISSUE TITLE
Support passthrough of cloud-init / cloud-config YAML

### ISSUE THREAD

**Issue by cevich** [CentOS-PaaS-SIG/linchpin#361]
This is required in some important cases, where partitioning or services must be disabled or configured prior to startup.  Otherwise, some mechanism of passing this in via image/volume attachment would be acceptable as well.

**Comment by greg-hellings** [comment]
I believe this is (or will be in 1.1) supported for open stack. I had
needed it, also, and sent in a PR for it. I don't know if that hit the
1.0.3 branch or not.

On Sep 16, 2017 3:22 PM, "Chris Evich" <notifications@github.com> wrote:

This is required in some important cases, where partitioning or services
must be disabled or configured prior to startup. Otherwise, some mechanism
of passing this in via image/volume attachment would be acceptable as well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CentOS-PaaS-SIG/linchpin/issues/361>, or mute the thread

**Comment by cevich** [comment]
Excellent, glad to hear it.

**Comment by samvarankashyap** [comment]
@cevich I am confident that cloud_init feature is included in 1.0.3

**Comment by cevich** [comment]
Is it documented (I couldn't find it)?

**Comment by samvarankashyap** [comment]
@cevich I am afraid  it's not .
As its just a userdata attribute to topology resource attribute. 
We will be working on documentation more. 
Please feel free to contribute  to documentation if you find some time :+1: 
ref : #291

**Comment by cevich** [comment]
One does not truly know something, until one can teach it.  Unfortunately, my n00b colors shine so brightly, the best I can manage ATM is spelling linchpin correctly ☹️

If I'm reading #291 correctly then (copying from the example), it would go something like:

```yaml
---
 topology_name: "example_topo"
 site: "qeos"
 resource_groups:
   -
     resource_group_name: "testgroup1"
     res_group_type: "openstack"
     res_defs:
       -
         res_name: "ha_inst"
         flavor: "m1.small"
         res_type: "os_server"
         image: "rhel-6.5_jeos"
         count: 1
         userdata: |
             #cloud-config

             timezone: US/Eastern
             growpart:
                 mode: off
             ...
```
?

Or does it take a file path as input?
