### ISSUE TITLE
Provisioning an OpenStack server with multiple networks fails

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linchpin#384]
Provisioning a server with multiple NICs is supported by the upstream os_server module. However, it fails in Linchpin.

Sample topology that fails:
```yaml
---
topology_name: "cinch-test"
resource_groups:
  -
    resource_group_name: "cinch-group"
    resource_group_type: "openstack"
    resource_definitions:
      -
        name: "jmaster"
        flavor: "m1.large"
        type: "os_server"
        image: "rhel-7.4-server-x86_64-released"
        count: 1
        keypair: "<snipped>"
        networks:
          - QE
          - QE
          - QE
    credentials:
      filename: "cinch.yml"
      profile: "ci-rhos"
```
Those arguments do work when passed to os_server (network arguments need to be adjusted to be ``net-name: QE`` instead of a string for the upstream module). Error message received is:

```
TASK [openstack : provision/teardown os_server resources with provided auth] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "No port on server <uuid> was found matching your NAT destination network <uuid>. Please  check your config"}
```

I experimented with specifying the fip_pool as well. That still provides the same error message, even when attempting to attach a floating IP from a network other than the one the error message is reporting against. Again, the native module in Ansible does not suffer from this deficiency and attaches a floating IP automatically.

NOTE: The server does come up with three IP addresses attached, as requested, but linchpin fails to attach a floating IP address and exits with the above error message.

**Comment by herlo** [comment]
I am not able to replicate this issue. I just provisioned two nodes, one of which has two networks listed. The result was successful.

```
---
topology_name: os-single
resource_groups:
  - resource_group_name: os-server
    resource_group_type: openstack
    resource_definitions:
      - name: database
        type: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 1
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
        fip_pool: 10.8.240.0
      - name: frontend
        type: os_server
        flavor: m1.small
        image: Fedora-Cloud-Base-26-compose-latest
        count: 1
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
          - atomic-e2e-jenkins-test
        fip_pool: 10.8.240.0
    credentials:
      filename: clouds.yaml
      profile: ci-rhos
```

```
$ openstack server --os-cloud ci-rhos list
+--------------------------------------+--------------------------------+--------+--------------------------------------------------------------------+-------------------------------------+
| ID                                   | Name                           | Status | Networks                                                           | Image Name                          |
+--------------------------------------+--------------------------------+--------+--------------------------------------------------------------------+-------------------------------------+
| a78a0084-4e53-4600-83a5-1fee7a4ce2a1 | frontend-b784-1                | ACTIVE | atomic-e2e-jenkins-test=172.16.171.18, 172.16.171.10, 10.8.245.178 | Fedora-Cloud-Base-26-compose-latest |
| eabbeca2-8216-464c-8556-3aef35ad7820 | database-b784-1                | ACTIVE | atomic-e2e-jenkins-test=172.16.171.11, 10.8.245.229                | CentOS-7-x86_64-GenericCloud-1612 
```
