### ISSUE TITLE
Provisioning using libvirt fails 

### ISSUE THREAD

**Issue by mrniranjan** [CentOS-PaaS-SIG/linchpin#416]
Provisioning using libvirt is failing with below error:

```
TASK [libvirt : define node when the cloud_config not defined] *******************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: libvirtError: internal error: Unable to parse URI {'count': 1, 'res_type': 'libvirt_node', 'uri': 'qemu:///system', 'networks': [{'name': 'linchpin-sssd'}], 'res_name': 'master', 'vcpus': 1, 'memory': 1024, 'arch': 'x86_64', 'image_src': 'file:///tmp/Fedora-Cloud-Base-27-1.6.x86_64.qcow2'}
failed: [localhost] (item=[u'qemu:///system', {u'count': 1, u'res_type': u'libvirt_node', u'uri': u'qemu:///system', u'networks': [{u'name': u'linchpin-sssd'}], u'res_name': u'master', u'vcpus': 1, u'memory': 1024, u'arch': u'x86_64', u'image_src': u'file:///tmp/Fedora-Cloud-Base-27-1.6.x86_64.qcow2'}, 0, u'/var/lib/libvirt/images/linchpin/', u'qcow2']) => {"changed": false, "definition": ["qemu:///system", {"arch": "x86_64", "count": 1, "image_src": "file:///tmp/Fedora-Cloud-Base-27-1.6.x86_64.qcow2", "memory": 1024, "networks": [{"name": "linchpin-sssd"}], "res_name": "master", "res_type": "libvirt_node", "uri": "qemu:///system", "vcpus": 1}, 0, "/var/lib/libvirt/images/linchpin/", "qcow2"], "msg": "internal error: Unable to parse URI {'count': 1, 'res_type': 'libvirt_node', 'uri': 'qemu:///system', 'networks': [{'name': 'linchpin-sssd'}], 'res_name': 'master', 'vcpus': 1, 'memory': 1024, 'arch': 'x86_64', 'image_src': 'file:///tmp/Fedora-Cloud-Base-27-1.6.x86_64.qcow2'}"}
        to retry, use: --limit @/opt/linchpin_dir/lib/python2.7/site-packages/linchpin/provision/site.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=49   changed=5    unreachable=0    failed=1   

hook postinv initiated
hook postup initiated

Target                  Run ID  uHash   Exit Code 
-------------------------------------------------
example_target              15   b5e8           2
```

Topology File:

```
topology_name: "libvirt"
resource_groups:
  -
    resource_group_name: "libvirt1"
    res_group_type: "libvirt"
    res_defs:

      - res_name: "linchpin-sssd"
        res_type: "libvirt_network"
        ip: 192.168.71.100
        dhcp_start: 192.168.71.101
        dhcp_end: 192.168.71.112

      - res_name: "master"
        res_type: "libvirt_node"
        uri: 'qemu:///system'
        count: 1
        image_src: 'file:///tmp/Fedora-Cloud-Base-27-1.6.x86_64.qcow2'
        memory: 1024
        vcpus: 1
        arch: x86_64
        networks:
          - name: linchpin-sssd

```
Layouts file:

```
(linchpin_dir) [root@mgmt3 test]# cat layouts/example-layout.yml 
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 1
      host_groups:
        - example
```
Versions:
linchpin (1.2.0)
libvirt-python (3.9.0)
