### ISSUE TITLE
RFE: support for beaker LIKE % operator

### ISSUE THREAD

**Issue by jpryor-rh** [CentOS-PaaS-SIG/linchpin#463]
From https://beaker-project.org/docs/whats-new/release-21.html#beaker-21-1
> #1010355: The --hostrequire option for workflow commands now supports the like operator, for example: --hostrequire 'hostname like %.example.com'.

This is from a working beaker job's XML:
```xml
<hostRequires>
  <and>
    <arch op="=" value="x86_64"/>
    <memory op="&gt;=" value="60000"/>
    <hostname op="like" value="node%.lab.redhat.com"/>
  </and>
  <system_type value="Machine"/>
</hostRequires>
```
for example it will choose an available host from hostnames node01 through node22.

**Comment by seandst** [comment]
This should already be supported. In the topology, the hostrequires section should look like:
```yaml
            hostrequires:
              - tag: arch
                op: "="
                value: x86_64
              - tag: memory
                op: ">="
                value: "60000"
              - tag: hostname
                op: like
                value: node%.lab.redhat.com
```

Note that beaker is sensitive to the case of the operator. `like` should work, `LIKE` will not.
