### ISSUE TITLE
provision with linchpin 1.5.1.1 creates more beaker jobs than recipe requested

### ISSUE THREAD

**Issue by danalanerh** [CentOS-PaaS-SIG/linchpin#478]
Using the following pinfile/topology and layout causes more beaker jobs than recipie sets, including multiple for each host. The 1st 3 complete and reserve the host, but them new jobs are queued up for the same hosts, resulting in the job stalling waiting for hosts to be free, then timing out and failing; Eventually the 2nd set of jobs times out and results in a failed run with no inventory file.

PinFile;
[PinFile.txt](https://github.com/CentOS-PaaS-SIG/linchpin/files/1729095/PinFile.txt)
topology;
[HCI_pod3_rdu_730_topology.yml.txt](https://github.com/CentOS-PaaS-SIG/linchpin/files/1729100/HCI_pod3_rdu_730_topology.yml.txt)
layout:
[HCI_pod3_layout.yml.txt](https://github.com/CentOS-PaaS-SIG/linchpin/files/1729102/HCI_pod3_layout.yml.txt)
output;
[linchpinOutput.txt](https://github.com/CentOS-PaaS-SIG/linchpin/files/1729113/linchpinOutput.txt)

**Comment by herlo** [comment]
Hi @danalanerh,

Is there something wrong with combining the recipesets? I'm not sure it solves the problem specifically, but doing this may ease your pain a little. LinchPin reads the items from top down, so the layouts should still be applied the same way.

```
---
topology_name: HCI_pod3
resource_groups:
  - resource_group_name: master
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        job_group: "CS&S"
        whiteboard: HCI Pod3 master - Provisioned with linchpin
        recipesets:
          - distro: RHEL-7.4
            arch: x86_64
            variant: Server
            count: 1
            hostrequires:
              - tag: pool
                op: "="
                value: "CS&S"
              - tag: hostname
                op: like
                # For testing only. Eventually, these will get more generic
                value: "dell-per730-01%.css.lab.eng.rdu2%"
          - distro: RHEL-7.4
            arch: x86_64
            variant: Server
            count: 1
            hostrequires:
              - tag: pool
                op: "="
                value: "CS&S"
              - tag: hostname
                op: like
                value: "dell-per730-02%.css.lab.eng.rdu2%"
          - distro: RHEL-7.4
            arch: x86_64
            variant: Server
            count: 1
            hostrequires:
              - tag: pool
                op: "="
                value: "CS&S"
              - tag: hostname
                op: like
                value: "dell-per730-03%.css.lab.eng.rdu2%"
```

**Comment by danalanerh** [comment]
It's a good question. In this case, I need them separate in the inventory file and originally I couldn't get them to be separate with a single recipe set. If there's a better way to do it, I'm open.

**Comment by herlo** [comment]
@danalanerh can you provide me with an example inventory file you need? I'm certain we can help get this where you want it. LinchPin v1.5+ provides some nice new features that may benefit you with regard to inventory generation and resource creation.

**Comment by danalanerh** [comment]
This is the resulting inventory file. Even though the recipes are the same, need to have 2 different host groups in this case.

[HCI_pod3_730 .inventory.txt](https://github.com/CentOS-PaaS-SIG/linchpin/files/1729235/HCI_pod3_730.inventory.txt)

**Comment by herlo** [comment]
When you say '2 different host groups in this case', to which groups are you referring? It doesn't matter how you allocate the resources. It only matters the order in which they are allocated lines up with how the inventory is generated.

For example, if you had this inventory layout:

```
---
inventory_layout:
  hosts:
    master:
      count: 1
      host_groups:
        - master
        - certificate_authority
    node_1:
      host_groups:
        - nodes
```

And a topology like so:

```
---
topology_name: HCI_pod3
resource_groups:
  - resource_group_name: master
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        job_group: "CS&S"
        whiteboard: HCI Pod3 master - Provisioned with linchpin
        recipesets:
          - distro: RHEL-7.4
            arch: x86_64
            variant: Server
            count: 1
            hostrequires:
              - tag: pool
                op: "="
                value: "CS&S"
              - tag: hostname
                op: like
                # For testing only. Eventually, these will get more generic
                value: "dell-per730-01%.css.lab.eng.rdu2%"
          - distro: RHEL-7.4
            arch: x86_64
            variant: Server
            count: 1
            hostrequires:
              - tag: pool
                op: "="
                value: "CS&S"
              - tag: hostname
                op: like
                value: "dell-per730-02%.css.lab.eng.rdu2%"
```
When those two nodes were provisioned in LinchPin, let's say they come out, in order, with the following host names:

```
dell-per730-01.css.lab.eng.rdu2.redhat.com
dell-per730-02.css.lab.eng.rdu2.redhat.com
```
The resulting inventory would be something like:

```
[master]
dell-per730-01.css.lab.eng.rdu2.redhat.com

[certificate_authority]
dell-per730-01.css.lab.eng.rdu2.redhat.com

[nodes]
dell-per730-02.css.lab.eng.rdu2.redhat.com

[all]
dell-per730-01.css.lab.eng.rdu2.redhat.com
dell-per730-02.css.lab.eng.rdu2.redhat.com
```
The thing to keep in mind is not so much how the resources are created, but how they are returned from your provisioner. They should come back in a deterministic order and should be generated in the same way each time.

In my mind, the example I gave in the previous comment should be equivalent to the one you were initially attempting to use. I can see why you'd want to separate them out logically for your sanity, but it only means more typing [and possibly more typos. :) ]

One note here. I didn't test these examples, so there may be errors in them, but the intent is correct.
