### ISSUE TITLE
Openstack provider should be able to create and attach volumes to a VM

### ISSUE THREAD

**Issue by scoheb** [CentOS-PaaS-SIG/linchpin#479]
We have a use case where we need to run a test with a VM that has a large volume.
We would like to be able to specify this need in the openstack topology.

parameters to define:

1. Volume size
2. Volume name

**Comment by greg-hellings** [comment]
%subject says "Openshift" but the mention of "VM" and %body indicate OpenStack. I presume OpenStack is correct?

**Comment by dyasny** [comment]
Looks like the same problem exists with the libvirt provisioner, should I open a separate issue for that?

**Comment by herlo** [comment]
@dyasny yes. Please open a separate issue. Thanks

**Comment by scoheb** [comment]
not sure this should be closed....

**Comment by herlo** [comment]
@scoheb Why not? The feature is in place now. It is now available in the develop tree and will be in the 1.5.2 release.

**Comment by lukas-bednar** [comment]
I have an use-case where I want to create 3 VMs, and each VM should have 3 disks (vda - system, vdb - docker-storage, vdc - gluster bucket). None of these disk (volumes) exist in openstack provider yet.
In total, it is 3 VMs and 9 disks. That means I need ask for 6 extra volumes, and attach them to relevant VMs.
How can I reference created volume, to VM?
I have following topology file, I put `<<<` marks where I miss something to achieve my goal.

```yaml
---
topology_name: my_cluster
resource_groups:
  - resource_group_name: openstack
    resource_group_type: openstack
    resource_definitions:
      - name: volume
        role: os_volume
        size: 20
        count: 6  # <<< HERE I ASK FOR 6 VOLUMES TO BE CREATED
      - name: master
        type: os_server
        flavor: t2.medium
        image: cesntos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - name: volume-for-docker-storage-X  # <<< I DON'T KNOW NAME OF VOLUME WHICH WAS CREATED.
            device_name: /dev/sdb # <<< IN ADDITION, I WOULD LIKE TO SPECIFY PATH TO DEVICE

          - name: volume-for-gluster-replica-bucket-X  # <<<  SAME HERE
            device_name: /dev/sdc  # <<< SAME HERE
      - name: node
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 2
        volumes:
          - name: volume-for-docker-storage-X  # <<< I DON'T KNOW NAME OF VOLUME WHICH WAS CREATED.
            device_name: /dev/sdb # <<< IN ADDITION, I WOULD LIKE TO SPECIFY PATH TO DEVICE

          - name: volume-for-gluster-replica-bucket-X  # <<<  SAME HERE
            device_name: /dev/sdc  # <<< SAME HERE
    credentials:
      filename: clouds.yml
      profile: centralci
```

**Comment by arilivigni** [comment]
@herlo can you get @lukas-bednar an answer for his use case.  I know adding volumes got merged but maybe you can help him with the topology he provided.

**Comment by herlo** [comment]
@lukas-bednar I see your use case, and believe it will work in this way.

I've created a topology that looks like this:

```
---
topology_name: os-single-new
resource_groups:
  - resource_group_name: os-server-enw
    resource_group_type: openstack
    resource_definitions:
      - name: volume-a
        role: os_volume
        size: 1
        count: 1
      - name: frontend
        role: os_server
        flavor: m1.small
        image: Fedora-Cloud-Base-26-compose-latest
        count: 1
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
        fip_pool: 10.8.240.0
        volumes:
          - volume-a_0
    credentials:
      filename: clouds.yaml
      profile: ci-rhos
```
What you may notice is that I created a single volume, just like you have in your topology. The only real difference is the number of volumes/instances created.

In this case, I create an os_volume named 'volume-a'. Automatically, linchpin appends a count to the end of it, zero-based. To attach it to the os_server, I just give the name of the expected volume. In this case, 'volume-a_0'. 

With your case, you might want to create two separate resources for volumes, then attach the volume by name to your specific instances. Something like this would work.

```
---
topology_name: my_cluster
resource_groups:
  - resource_group_name: openstack
    resource_group_type: openstack
    resource_definitions:
      - name: master_volume
        role: os_volume
        size: 20
        count: 3
      - name: node_volume
        role: os_volume
        size: 10
        count: 3
      - name: master
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - master_volume_0
          - master_volume_1
          - master_volume_2
      - name: node
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 2
        volumes:
          - node_volume_0
          - node_volume_1
          - node_volume_2
    credentials:
      filename: clouds.yml
      profile: centralci
```

LinchPin uses a top-down mechanism to assign items to their counterparts, so the disk component you are trying to add will automatically start with the next disk and assign it. 

I took a look at the ansible module for os_server[1].  There didn't seem to be a way to assign a specific device to a specific volume, at least not that I can see.

I hope this helps.

@herlo

1 - http://docs.ansible.com/ansible/latest/modules/os_server_module.html

**Comment by lukas-bednar** [comment]
@herlo Hi, thanks for putting this together. 
I believe that in case bellow, the nodes will share these volumes.
```
      - name: node
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 2
        volumes:
          - node_volume_0
          - node_volume_1
          - node_volume_2
```
I want something like, where every node will have one extra dedicated disk for docker storage and second dedicated disk for gluster.
Something like this:
```
      - name: master1
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - volume_0  # for gluster
          - volume_1  # for docker
      - name: node1
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - volume_2  # for gluster
          - volume_3  # for docker
      - name: node2
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - volume_4  # for gluster
          - volume_5  # for docker
```
I will probably have to go with this verbose way  to achieve that .

Regarding to attaching volume as a specific device, is possible as a part of attaching operation:
http://docs.ansible.com/ansible/latest/modules/os_server_volume_module.html

In order to summarize it, by making my topology verbose, and define my nodes there one by one with relevant volume_X & volume_X+1 ... but still I need to be able to attach it with specific device, like `/dev/sdb` for instance.

Once more thanks for your input!
