### ISSUE TITLE
Need instance_tags on linchpin AWS instances

### ISSUE THREAD

**Issue by flowerncsu** [CentOS-PaaS-SIG/linchpin#503]
As per the ansible EC2 module documentation (http://docs.ansible.com/ansible/latest/ec2_module.html), instance_tags is an available parameter, but linchpin does not accept that parameter. We need that parameter available.

Example usage:
```
instance_tags:
  color: blue
  shape: oval
```

**Comment by herlo** [comment]
This also may fix #527 by reworking the instance_tags field (https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/provision/roles/aws/tasks/provision_aws_ec2.yml#L21) into a simple list, using set_fact above this task.

Something like:

```
- name: set instance_tags
  set_fact:
    res_def_instance_tags: []

- name: set instance_tags
  set_fact:
    res_def_instance_tags: "[{{ name }}] + [{{ res_grp_name }}] + {{ res_def['instance_tags'] }}"
```

Note: I'm not 100% on the list items above, so that may need to be adjusted.
