### ISSUE TITLE
Context distiller puts out no output when one resource fails

### ISSUE THREAD

**Issue by flowerncsu** [CentOS-PaaS-SIG/linchpin#531]
Two pinfiles tested:
```
---
pass_aws:
  topology: topology-0.yml
```
and
```
---
pass_aws:
  topology: topology-0.yml
fail_aws:
  topology: fail_aws.yml
```
`topology-0` successfully creates an aws instance. `fail_aws` is:
```
---
topology_name: ec2-new
resource_groups:
  - resource_group_name: "aws"
    resource_group_type: "aws"
    resource_definitions:
      - name: "ci-testbox"
        flavor: "m1.small"
        role: "aws_ec2"

        region: "us-east-1"
        image: "not-an-image"
        security_group: "default"
        count: 1
```
When using the PinFile which includes `fail_aws`, the `linchpin.distilled` file is not created, regardless of whether there was a previous `linchpin.distilled`. When using the PinFile without `fail_aws`, `linchpin.distilled` is created if there is not one, and overwritten if there is (which is the desired behavior).
