### ISSUE TITLE
When attaching volumes in openstack, use os_server_volume module

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linchpin#544]
Per discussions with @lukas-bednar around  #479, this ticket has been created. I've taken his example from the previous issue.

I have an use-case where I want to create 3 VMs, and each VM should have 3 disks (vda - system, vdb - docker-storage, vdc - gluster bucket). None of these disk (volumes) exist in openstack provider yet.
In total, it is 3 VMs and 9 disks. That means I need ask for 6 extra volumes, and attach them to relevant VMs.
How can I reference created volume, to VM?
I have following topology file, I put `<<<` marks where I miss something to achieve my goal.

```yaml
---
topology_name: my_cluster
resource_groups:
  - resource_group_name: openstack
    resource_group_type: openstack
    resource_definitions:
      - name: volume
        role: os_volume
        size: 20
        count: 6  # <<< HERE I ASK FOR 6 VOLUMES TO BE CREATED
      - name: master
        type: os_server
        flavor: t2.medium
        image: cesntos-7.4-server-x86_64-latest
        count: 1
        volumes:
          - name: volume-for-docker-storage-X  # <<< I DON'T KNOW NAME OF VOLUME WHICH WAS CREATED.
            device_name: /dev/sdb # <<< IN ADDITION, I WOULD LIKE TO SPECIFY PATH TO DEVICE

          - name: volume-for-gluster-replica-bucket-X  # <<<  SAME HERE
            device_name: /dev/sdc  # <<< SAME HERE
      - name: node
        type: os_server
        flavor: t2.medium
        image: centos-7.4-server-x86_64-latest
        count: 2
        volumes:
          - name: volume-for-docker-storage-X  # <<< I DON'T KNOW NAME OF VOLUME WHICH WAS CREATED.
            device_name: /dev/sdb # <<< IN ADDITION, I WOULD LIKE TO SPECIFY PATH TO DEVICE

          - name: volume-for-gluster-replica-bucket-X  # <<<  SAME HERE
            device_name: /dev/sdc  # <<< SAME HERE
    credentials:
      filename: clouds.yml
      profile: centralci
```

Currently, when the volumes are attached, they must first be detached before they are destroyed. If they don't, linchpin fails to destroy the server and volume and exits. Using [the os_server_volume](http://docs.ansible.com/ansible/latest/modules/os_server_volume_module.html) module would be a better way to attach/detach the volume from the instance.
