### ISSUE TITLE
Distiller does not work with multiple instance counts: os_server

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#573]
### Pinfile 
```yaml
---
dummy_target:
  topology: oss-topology.yml
  layout: dummy-layout.yml
```

### Topology: 
```yaml
---
topology_name: os-single-new
resource_groups:
  - resource_group_name: os-server-new
    resource_group_type: openstack
    resource_definitions:
      - name: testinstance-sk
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 2
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
      - name: anotestinst-sk
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 2
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
    credentials:
      filename: clouds.yaml
      profile: default
  - resource_group_name: os-server-new
    resource_group_type: openstack
    resource_definitions:
      - name: testins-sk
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 2
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
      - name: antst-sk
        role: os_server
        flavor: m1.small
        image: CentOS-7-x86_64-GenericCloud-1612
        count: 1
        keypair: ci-factory
        networks:
          - atomic-e2e-jenkins-test
    credentials:
      filename: clouds.yaml
      profile: default
```

### Layout:
```yaml
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 2
      host_groups:
        - example
```

### Expected distiller output:
```json
{
    "dummy_target": [{
        "private_v4": "172.16.171.3",
        "public_v4": "10.8.247.226",
        "interface_ip": "10.8.247.226",
        "id": "9e0cb388-117b-4afc-b31b-1cdb9983c511",
        "name": "testinstance-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.19",
        "public_v4": "10.8.241.128",
        "interface_ip": "10.8.241.128",
        "id": "a0141558-070a-4b81-8d6e-75fadf36d861",
        "name": "testinstance-sk-50b651-2"
    }, {
        "private_v4": "172.16.171.8",
        "public_v4": "10.8.251.8",
        "interface_ip": "10.8.251.8",
        "id": "6b4558eb-7e99-4ba7-a182-1e138a40cf94",
        "name": "anotestinst-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.30",
        "public_v4": "10.8.250.66",
        "interface_ip": "10.8.250.66",
        "id": "aa5b96fa-9d6e-4196-89bc-aa48f56f8b6b",
        "name": "anotestinst-sk-50b651-2"
    }, {
        "private_v4": "172.16.171.13",
        "public_v4": "10.8.250.106",
        "interface_ip": "10.8.250.106",
        "id": "0f6b825a-2906-465b-a171-54d8e084cfe8",
        "name": "testins-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.27",
        "public_v4": "10.8.250.107",
        "interface_ip": "10.8.250.107",
        "id": "62859332-ba2b-4b57-a80a-bdce44fa446e",
        "name": "testins-sk-50b651-2"
    }, {
        "private_v4": "172.16.171.25",
        "public_v4": "10.8.250.6",
        "interface_ip": "10.8.250.6",
        "id": "e375a4c7-45fc-43b9-9c73-87460f0e29ee",
        "name": "antst-sk-50b651-1"
    }]
}
```

### Actual distiller output: 

```json
{
    "dummy_target": [{
        "private_v4": "172.16.171.3",
        "public_v4": "10.8.247.226",
        "interface_ip": "10.8.247.226",
        "id": "9e0cb388-117b-4afc-b31b-1cdb9983c511",
        "name": "testinstance-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.8",
        "public_v4": "10.8.251.8",
        "interface_ip": "10.8.251.8",
        "id": "6b4558eb-7e99-4ba7-a182-1e138a40cf94",
        "name": "anotestinst-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.13",
        "public_v4": "10.8.250.106",
        "interface_ip": "10.8.250.106",
        "id": "0f6b825a-2906-465b-a171-54d8e084cfe8",
        "name": "testins-sk-50b651-1"
    }, {
        "private_v4": "172.16.171.25",
        "public_v4": "10.8.250.6",
        "interface_ip": "10.8.250.6",
        "id": "e375a4c7-45fc-43b9-9c73-87460f0e29ee",
        "name": "antst-sk-50b651-1"
    }]
}
```
### Description 
As we can see the expected distiller output is total 7 instances . But the actual distiller output has only 4 instances distilled . The output mentioned is tested on os_server instances . The other types of providers should be tested too.
