### ISSUE TITLE
Vars supplied via -d switch aren't present in the generated inventory

### ISSUE THREAD

**Issue by dyasny** [CentOS-PaaS-SIG/linchpin#584]
I create a yaml file containing a parameter I need passed to the layout, but it never shows up after provisioning. Details:

Pinfile:
```yaml
---
my_cluster:
  topology: my-cluster.yml
  layout: my-cluster.yml

my_libvirt_cluster:
  topology: my-libvirt-cluster.yml
  layout: my-cluster.yml
```

Topology:
```yaml
---
topology_name: my_libvirt_cluster
resource_groups:
  - resource_group_name: libvirt
    resource_group_type: libvirt
    resource_definitions:
      - role: libvirt_node
        name: master
        uri: qemu:///system
        count: 1
        image_src: file:///var/lib/libvirt/images/base_image
        memory: 16384
        vcpus: 4
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default

      - role: libvirt_node
        name: node
        uri: qemu:///system
        count: 2
        image_src: file:///var/lib/libvirt/images/base_image
        memory: 8196
        vcpus: 4
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default
```
Layout:
```yaml
inventory_layout:
#  inventory_file: my-inventory.inv
  vars:
    hostname: __IP__
  hosts:
    "{{ executor_name }}-master":
      count: 1
      host_groups:
        - masters
        - etcd
        - nodes
        - nfs
        - glusterfs
    "{{ executor_name }}-node":
      count: 2
      host_groups:
        - nodes
        - glusterfs
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
        - etcd
        - nfs
        - glusterfs
      vars:
        ansible_ssh_user: root
        containerized: true
        openshift_version: "3.9.25"
        openshift_release: "v3.9"
        openshift_image_tag: "v3.9.25"
        openshift_schedulable: true
        osm_default_node_selector: ""
        openshift_node_labels: "{'region': 'infra','zone': 'default', 'node-role.kubernetes.io/compute': 'true'}"
        openshift_deployment_type: openshift-enterprise
        openshift_clock_enabled: true
        openshift_master_identity_providers: "[{'name': 'allow_all_auth', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]"
        openshift_disable_check: "memory_availability,disk_availability"
        openshift_enable_excluders: false
        template_service_broker_install: false
        openshift_use_manageiq: false
        openshift_install_examples: false
->     openshift_master_default_subdomain: "cloudapps.{{ domain }}"
->     openshift_hosted_registry_routehost: "registry.cloudapps.{{ domain }}"

        openshift_hosted_etcd_storage_kind: nfs
        openshift_hosted_etcd_storage_nfs_options: "*(rw,root_squash,sync,no_wdelay)"
        openshift_hosted_etcd_storage_nfs_directory: "/opt/osev3-etcd"
        openshift_hosted_etcd_storage_volume_name: "etcd-vol2"
        openshift_hosted_etcd_storage_access_modes: "['ReadWriteOnce']"
        openshift_hosted_etcd_storage_volume_size: "1100M"
        openshift_hosted_etcd_storage_labels: "{'storage': 'etcd'}"

        ansible_service_broker_local_registry_whitelist: "[\".*-apb$\"]"

        docker_dev: "/dev/vdb"
        glusterfs_devices: "['/dev/vdc']"

        # webconsole
        openshift_web_console_prefix: "jniederm/origin-"
        openshift_web_console_version: "demo-v10"

        # cns
        openshift_storage_glusterfs_namespace: "app-storage"
        openshift_storage_glusterfs_storageclass: true
        openshift_storageclass_default: false
        openshift_storage_glusterfs_storageclass_default: true
        openshift_storage_glusterfs_block_deploy: false
```

my_cluster_vars.yml 
```yaml
domain: example.com
```

command:
```sh
linchpin -w $myDIR/linchpin-ws \
  -d @$myDIR/workspace/my_cluster_vars.yml \
  up my_libvirt_cluster
```

Resulting inventory:
```
[OSEv3:children]
masters
nodes
etcd
nfs
glusterfs

[OSEv3:vars]
openshift_version = 3.9.25
openshift_storage_glusterfs_namespace = app-storage
openshift_master_default_subdomain = cloudapps.                                         <----
openshift_install_examples = False   
template_service_broker_install = False
openshift_hosted_etcd_storage_nfs_options = *(rw,root_squash,sync,no_wdelay)
openshift_disable_check = memory_availability,disk_availability
openshift_release = v3.9
glusterfs_devices = ['/dev/vdc']
docker_dev = /dev/vdb
openshift_storage_glusterfs_storageclass = True
openshift_hosted_registry_routehost = registry.cloudapps.                              <----
openshift_hosted_etcd_storage_kind = nfs
containerized = True
openshift_hosted_etcd_storage_labels = {'storage': 'etcd'}
openshift_storageclass_default = False
openshift_hosted_etcd_storage_volume_size = 1100M
openshift_hosted_etcd_storage_volume_name = etcd-vol2
openshift_image_tag = v3.9.25
openshift_hosted_etcd_storage_nfs_directory = /opt/osev3-etcd
openshift_clock_enabled = True
openshift_storage_glusterfs_block_deploy = False
osm_default_node_selector = 
openshift_node_labels = {'region': 'infra','zone': 'default', 'node-role.kubernetes.io/compute': 'true'}
openshift_web_console_version = demo-v10
openshift_deployment_type = openshift-enterprise
openshift_storage_glusterfs_storageclass_default = True
openshift_enable_excluders = False
openshift_master_identity_providers = [{'name': 'allow_all_auth', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]
openshift_schedulable = True
openshift_use_manageiq = False
ansible_ssh_user = root
ansible_service_broker_local_registry_whitelist = [".*-apb$"]
openshift_web_console_prefix = jniederm/origin-
openshift_hosted_etcd_storage_access_modes = ['ReadWriteOnce']

[glusterfs]
192.168.122.221 hostname=192.168.122.221
192.168.122.164 hostname=192.168.122.164
192.168.122.35 hostname=192.168.122.35

[masters]
192.168.122.221 hostname=192.168.122.221

[nfs]
192.168.122.221 hostname=192.168.122.221

[nodes]
192.168.122.221 hostname=192.168.122.221
192.168.122.164 hostname=192.168.122.164
192.168.122.35 hostname=192.168.122.35

[etcd]
192.168.122.221 hostname=192.168.122.221

[all]
192.168.122.221 hostname=192.168.122.221
192.168.122.164 hostname=192.168.122.164
192.168.122.35 hostname=192.168.122.35
```

The offending lines are marked with --->
