### ISSUE TITLE
No IPs are rendered in inventory file if auto_ip:no is set for openstack provider

### ISSUE THREAD

**Issue by lukas-bednar** [CentOS-PaaS-SIG/linchpin#596]
linchpin 1.5.4

I have following topology using openstack provider, and I don't want that VM will get floating IPs.
It is enough for my usecase to use internal IPs only. So I am setting `auto_ip: no` to skip FIP assignment. 
```yaml
---
topology_name: my_cluster
resource_groups:
  - resource_group_name: openstack
    resource_group_type: openstack
    resource_definitions:
      - name: "{{ executor_name }}-master"
        type: os_server
        flavor: w1.large
        image: "{{ image }}"
        count: 1
        keypair: "{{ keypair }}"
        networks:
          - "{{ network }}"
        auto_ip: no
        security_groups: "{{ security_group }}"
      - name: "{{ executor_name }}-node"
        type: os_server
        flavor: w1.large
        image: "{{ image }}"
        count: 2
        keypair: "{{ keypair }}"
        networks:
          - "{{ network }}"
        auto_ip: no
        security_groups: "{{ security_group }}"
    credentials:
      filename: clouds.yml
      profile: "{{ os_cloud }}"
```
and I have following layout where I want to render provisioned VMs with internal IPs
```yaml
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    "{{ executor_name }}-master":
      count: 1
      host_groups:
        - masters
        - etcd
        - nodes
        - nfs
        - glusterfs
    "{{ executor_name }}-node":
      count: 2
      host_groups:
        - nodes
        - glusterfs
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
        - etcd
        - nfs
        - glusterfs
```
but unfortunately the generated inventory file is empty
```
[glusterfs]
 hostname=

[masters]
 hostname=

[nfs]
 hostname=

[nodes]
 hostname=

[etcd]
 hostname=

[all]
 hostname=
```

Could you please help me to achieve my use case ?
