### ISSUE TITLE
Layout: add ability to set variable per node in-line

### ISSUE THREAD

**Issue by lukas-bednar** [CentOS-PaaS-SIG/linchpin#607]
Hi,

The feature I am looking forward here is that I need to set some variable (`openshift_node_group_name`) to different values (`node-config-nodes` or `node-config-masters`) depending on hostgroup where relevant node belongs to .

Example:
```ini
[OSEv3:children]
masters
nodes

[OSEv3:vars]
openshift_node_groups = [{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

[masters]
10.8.246.240 hostname=10.8.246.240 openshift_node_group_name=node-config-masters

[nodes]
10.8.252.226 hostname=10.8.252.226 openshift_node_group_name=node-config-nodes
10.8.252.231 hostname=10.8.252.231 openshift_node_group_name=node-config-nodes
10.8.246.240 hostname=10.8.246.240 openshift_node_group_name=node-config-nodes
```
What I tried to do was
```yaml
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    "{{ executor_name }}-master":
      count: 1
      host_groups:
        - masters
        - nodes
      vars:
          openshift_node_group_name: node-config-masters
    "{{ executor_name }}-node":
      count: 2
      host_groups:
        - nodes
      vars:
          openshift_node_group_name: node-config-nodes
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
      vars:
        openshift_node_groups: "[{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]"
```
But this configuration results in following inventory
```ini
[OSEv3:children]
masters
nodes

[OSEv3:vars]
openshift_node_groups = [{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

[masters:vars]
openshift_node_group_name=node-config-masters

[nodes:vars]
openshift_node_group_name=node-config-nodes

[masters]
10.8.246.240 hostname=10.8.246.240

[nodes]
10.8.252.226 hostname=10.8.252.226
10.8.252.231 hostname=10.8.252.231
10.8.246.240 hostname=10.8.246.240
```
Such configuration doesn't fit me because these `[nodes:vars]` & `[masters:vars]` sections hide `[OSEv3:vars]` for relevant machines and ansible will not see variables defined in this section ...

So I don't know how achieve that, maybe this is already possible, and I am just missing something ...

**Comment by lukas-bednar** [comment]
Could we add `kubevirt` label for it please?

**Comment by p3ck** [comment]
so I don't get any different behavior from ansible between the two inventories described above.
I ran the following:
`ansible -i inventory -m debug -a "var=hostvars[inventory_hostname]" OSEv3 | grep openshift_node_group_name
and
ansible -i inventory2 -m debug -a "var=hostvars[inventory_hostname]" OSEv3 | grep openshift_node_group_name`
 
Neither one showed a "openshift_node_group_name": "node-config-masters" because of the duplicate name/IP address.

Am I missing something?  Can you show me what you expect to see based on some debug commands?

Thanks

**Comment by lukas-bednar** [comment]
Hm, maybe I am facing ansible issue (not linchpin issue) :-/ ...

Having inventory like this (which I am able to render with linchpin now)
```ini
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_user = root
ansible_ssh_private_key_file = ~/.ssh/cnv-qe-jenkins.key
openshift_node_groups = [{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

[masters:vars]
openshift_node_group_name=node-config-masters

[nodes:vars]
openshift_node_group_name=node-config-nodes

[masters]
10.8.250.1

[nodes]
10.8.250.1
10.8.249.142
10.8.247.25
```
And I am getting output like this
```
PLAY [Test our inventory for masters] *********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [10.8.250.1]

TASK [Print openshift_node_group_name] ********************************************************************************************************************************************************
ok: [10.8.250.1] => {
    "openshift_node_group_name": "node-config-nodes"
}

TASK [Print openshift_node_groups] ************************************************************************************************************************************************************
ok: [10.8.250.1] => {
    "openshift_node_groups": [
        {
            "labels": [
                "node-role.kubernetes.io/master=true", 
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-masters"
        }, 
        {
            "labels": [
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-nodes"
        }
    ]
}

PLAY [Test our inventory for nodes] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [10.8.250.1]

TASK [Print openshift_node_group_name] ********************************************************************************************************************************************************
ok: [10.8.250.1] => {
    "openshift_node_group_name": "node-config-nodes"
}

TASK [Print openshift_node_groups] ************************************************************************************************************************************************************
ok: [10.8.250.1] => {
    "openshift_node_groups": [
        {
            "labels": [
                "node-role.kubernetes.io/master=true", 
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-masters"
        }, 
        {
            "labels": [
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-nodes"
        }
    ]
}

PLAY [Test our inventory for nodes] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [10.8.249.142]

TASK [Print openshift_node_group_name] ********************************************************************************************************************************************************
ok: [10.8.249.142] => {
    "openshift_node_group_name": "node-config-nodes"
}

TASK [Print openshift_node_groups] ************************************************************************************************************************************************************
ok: [10.8.249.142] => {
    "openshift_node_groups": [
        {
            "labels": [
                "node-role.kubernetes.io/master=true", 
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-masters"
        }, 
        {
            "labels": [
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-nodes"
        }
    ]
}

PLAY [Test our inventory for nodes] ***********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [10.8.247.25]

TASK [Print openshift_node_group_name] ********************************************************************************************************************************************************
ok: [10.8.247.25] => {
    "openshift_node_group_name": "node-config-nodes"
}

TASK [Print openshift_node_groups] ************************************************************************************************************************************************************
ok: [10.8.247.25] => {
    "openshift_node_groups": [
        {
            "labels": [
                "node-role.kubernetes.io/master=true", 
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-masters"
        }, 
        {
            "labels": [
                "node-role.kubernetes.io/infra=true", 
                "node-role.kubernetes.io/compute=true"
            ], 
            "name": "node-config-nodes"
        }
    ]
}

PLAY RECAP ************************************************************************************************************************************************************************************
10.8.247.25                : ok=3    changed=0    unreachable=0    failed=0   
10.8.249.142               : ok=3    changed=0    unreachable=0    failed=0   
10.8.250.1                 : ok=6    changed=0    unreachable=0    failed=0   
```

And I would expect in `PLAY [Test our inventory for masters] \ TASK [Print openshift_node_group_name] ` see `node-config-masters` instead of `node-config-nodes` ...
```
PLAY [Test our inventory for masters] *********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [10.8.250.1]

TASK [Print openshift_node_group_name] ********************************************************************************************************************************************************
ok: [10.8.250.1] => {
    "openshift_node_group_name": "node-config-masters"   # <<<< HERE
}
```
I will dig deeper, thanks for poke me forward ;-)

**Comment by p3ck** [comment]
@lukas-bednar - Are you all set?  Can I close this issue?

**Comment by lukas-bednar** [comment]
Unfortunately I am not. I still don't know how to render something like this:
```ini
[masters]
10.8.253.24 hostname=10.8.253.24

[nodes]
10.8.253.24 hostname=10.8.253.24
10.8.253.26 hostname=10.8.253.26 openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
10.8.244.34 hostname=10.8.244.34 openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
```

**Comment by samvarankashyap** [comment]
@lukas-bednar : I guess the following layouts might workout for you . 
Example layout 1: 
```yaml
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    "test-master":
      count: 1
      host_groups:
        - masters
        - nodes
        - nodelabelgroup1
      vars:
          openshift_node_group_name: node-config-masters
    "test-node":
      count: 2
      host_groups:
        - nodes
        - nodelabelgroup2
      vars:
          openshift_node_group_name: node-config-nodes
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
      vars:
        openshift_node_groups: "[{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]"
    nodelabelgroup1:
      vars: 
        openshift_node_labels: "\"{'region': 'infra', 'zone': 'default'}\""
    nodelabelgroup2:
      vars:
        openshift_node_labels: "\"{'region': 'primary', 'zone': 'east'}\""
```

##### As you can see in the above example I have created two separate node label groups to add group specific vars. If you would like to have only one var per node, You should be creating only 1 node per group. In above example I have created master nodelabelgroup1 for master and nodelabelgroup2 for other two nodes 

Example output : 
```
[OSEv3:children]
masters
nodes

[nodelabelgroup2:vars]
openshift_node_labels = "{'region': 'primary', 'zone': 'east'}"

[nodelabelgroup1:vars]
openshift_node_labels = "{'region': 'infra', 'zone': 'default'}"

[OSEv3:vars]
openshift_node_groups = [{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

[nodelabelgroup2]
web-cd3278-1.example.net hostname=web-cd3278-1.example.net
web-cd3278-2.example.net hostname=web-cd3278-2.example.net

[masters]
web-cd3278-0.example.net hostname=web-cd3278-0.example.net

[nodelabelgroup1]
web-cd3278-0.example.net hostname=web-cd3278-0.example.net

[nodes]
web-cd3278-0.example.net hostname=web-cd3278-0.example.net
web-cd3278-1.example.net hostname=web-cd3278-1.example.net
web-cd3278-2.example.net hostname=web-cd3278-2.example.net

[all]
web-cd3278-0.example.net hostname=web-cd3278-0.example.net
web-cd3278-1.example.net hostname=web-cd3278-1.example.net
web-cd3278-2.example.net hostname=web-cd3278-2.example.net
```

Example layout 2: 
if you would like to add a single variable to all the hosts : 

```yaml
inventory_layout:
  vars:
    hostname: __IP__
    openshift_node_labels: "\"{'region': 'infra', 'zone': 'default'}\""
  hosts:
    "test-master":
      count: 1
      host_groups:
        - masters
        - nodes
      vars:
          openshift_node_group_name: node-config-masters
    "test-node":
      count: 2
      host_groups:
        - nodes
      vars:
          openshift_node_group_name: node-config-nodes
  host_groups:
    OSEv3:
      children:
        - masters
        - nodes
      vars:
        openshift_node_groups: "[{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]"
```

Example output: 
```
[OSEv3:children]
masters
nodes

[OSEv3:vars]
openshift_node_groups = [{'name': 'node-config-masters', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']},{'name': 'node-config-nodes', 'labels': ['node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true']}]

[masters]
web-91c5d0-0.example.net hostname=web-91c5d0-0.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[nodes]
web-91c5d0-1.example.net hostname=web-91c5d0-1.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
web-91c5d0-0.example.net hostname=web-91c5d0-0.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
web-91c5d0-2.example.net hostname=web-91c5d0-2.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[all]
web-91c5d0-1.example.net hostname=web-91c5d0-1.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
web-91c5d0-0.example.net hostname=web-91c5d0-0.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
web-91c5d0-2.example.net hostname=web-91c5d0-2.example.net openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
```


###### In both the cases openshift should be able to recognize the node labels defined.
