### ISSUE TITLE
bkr topology: Introduce support for 'family' and 'tag' fields in bkr topology files

### ISSUE THREAD

**Issue by yashkmankad** [CentOS-PaaS-SIG/linchpin#612]
The Beaker (bkr) provider for linchpin currently supports using the 'distro' parameter under recipesets, but does not support 'family' and 'tag'.

Example beaker topology file with 'family' and 'tag' would look like:

```
---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: your-beaker-group
    recipesets:
      - family: RedHatEnterpriseLinuxServer6
        tag: RELEASED
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        count: 1
```

Related documentation about using the family and tag options with the Beaker (bkr) command line tool:
 * https://beaker-project.org/docs/man/bkr-distros-list.html#cmdoption-bkr-distros-list-family
 * https://beaker-project.org/docs/man/bkr-job-list.html#cmdoption-bkr-job-list-family
