### ISSUE TITLE
bkr topology:  the 'location' tag seems to be invalid in bkr topology files

### ISSUE THREAD

**Issue by yoguo** [CentOS-PaaS-SIG/linchpin#615]
```
---
topology_name: "bkr-test"
resource_groups:
  - resource_group_name: "bkr-test"
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        whiteboard: Provisioned with linchpin
        max_attempts: 240
        attempt_wait_time: 60
        cancel_message: Job cancelled on account of rain
        recipesets:
          - distro: RHEL-7.5
            arch: x86_64
            variant: Server
            count: 1
            name: rhel75
            keyvalue:
              - DISKSPACE>=200000
            bkr_data: lvm-on
            hostrequires:
              - tag: arch
                op: "="
                value: "X86_64"
              - tag: location
                op: like
                value: "%NAY%"
              - tag: memory
                op: ">="
                value: "1000"
          - distro: RHEL-7.5
            arch: x86_64
            variant: Server
            count: 1
            name: rhel75
            keyvalue:
              - DISKSPACE>=200000
            bkr_data: lvm-off
            hostrequires:
              - tag: arch
                op: "="
                value: "X86_64"
              - tag: location
                op: like
                value: "%NAY%"
              - tag: memory
                op: ">="
                value: "1000"
```

The ‘location‘ tag seems to be invalid.  The cisco-xxx-xx.rhts.eng.bos.redhat.com (location doesn't contain NAY)has been provisioned.  The location fag is not supported? or the topology file is not correct?Thanks.

linchpin version 1.5.4
