### ISSUE TITLE
beaker hostrequires force no longer working

### ISSUE THREAD

**Issue by spoore1** [CentOS-PaaS-SIG/linchpin#616]
Should the Beaker provider still support forcing a hostname in hostrequires?  It appears that it no longer works:

This is my topology file:

```
topology_name: beaker
resource_groups:
- resource_group_name: test_host
  resource_group_type: beaker
  resource_definitions:
  - role: bkr_server
    job_group: idm
    whiteboard: test_host
    recipesets:
    - name: test_host
      distro: RHEL-7.5%
      variant: Server
      arch: x86_64
      hostrequires:
      - force: hostname.fqdn.scrubbed
      count: 1
```

This is the failure I see when I run linchpin up:

```
TASK [beaker : provision beaker systems] **************************************************************
task path: /root/sctenv/pyvirt1/lib/python2.7/site-packages/linchpin/provision/roles/beaker/tasks/provision_resource_group.yml:2
failed: [localhost] (item={'role': u'bkr_server', 'whiteboard': u'test_host', 'job_group': u'idm', 'recipesets': [{'variant': u'Server', 'hostrequires': [{'force': u'hostname.fqdn.scrubbed'}], 'arch': u'x86_64', 'name': u'test_host', 'distro': u'RHEL-7.5%'}]}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "attempt_wait_time": 60, 
            "cancel_message": "Job canceled by LinchPin", 
            "job_group": "idm", 
            "max_attempts": 60, 
            "recipesets": [
                {
                    "arch": "x86_64", 
                    "distro": "RHEL-7.5%", 
                    "hostrequires": [
                        {
                            "force": "hostname.fqdn.scrubbed"
                        }
                    ], 
                    "name": "test_host", 
                    "variant": "Server"
                }
            ], 
            "state": "present", 
            "whiteboard": "test_host"
        }
    }, 
    "msg": "'tag'", 
    "res": {
        "job_group": "idm", 
        "recipesets": [
            {
                "arch": "x86_64", 
                "distro": "RHEL-7.5%", 
                "hostrequires": [
                    {
                        "force": "hostname.fqdn.scrubbed"
                    }
                ], 
                "name": "test_host", 
                "variant": "Server"
            }
        ], 
        "role": "bkr_server", 
        "whiteboard": "test_host"
    }
}
```

If I change my topology to instead use tag-op-value to define the host, it seems to work.  I'd like to be able to go back to using force though if this is a regression.

Thanks,
Scott
