### ISSUE TITLE
inventory_file relational path can break linchpin

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#617]
Setting `inventory_file` with relational path such as `beaker.yml`  will overwrite lincpin file `provision/beaker.yml`.

Linchpin version: 1.5.4
Example:
```
---
inventory_layout:
  inventory_file: beaker.yml
  vars:
    hostname: __IP__
    ansible_user: root
  hosts:
    example_shit:
      count: 1
      host_groups:
        - example
```
Running `linchpin up` will overwrite `~/.virtualenvs/linchpin/lib/python2.7/site-packages/linchpin/provision/beaker.yml` with the result inventory and thus breaking linchpin.

Expected result:
Workspace will be the relational path and `./beaker.yml` will be create or modified.
