### ISSUE TITLE
The inventory file just contains part of the output results when reserving machines from beaker

### ISSUE THREAD

**Issue by yoguo** [CentOS-PaaS-SIG/linchpin#630]
Hi,

I encountered a problem about linchpin tool（1.5.4）. I'd like to reserve two machines from beaker. The topology file is displayed as follows:

```
---
topology_name: "test-rhel7"
resource_groups:
  - resource_group_name: "test-rhel7"
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        whiteboard: Provisioned with linchpin
        max_attempts: 240
        attempt_wait_time: 60
        cancel_message: Job cancelled on account of rain
        recipesets:
          - distro: RHEL-7.5
            arch: x86_64
            variant: Server
            count: 1
            name: rhel75
            keyvalue:
              - DISKSPACE>=100000
            bkr_data: lvm-on
            hostrequires:
              - tag: arch
                op: "="
                value: "X86_64"
              - tag: memory
                op: ">="
                value: "1000"
          - distro: RHEL-7.5
            arch: x86_64
            variant: Server
            count: 1
            name: rhel75
            keyvalue:
              - DISKSPACE>=100000
            bkr_data: lvm-off
            hostrequires:
              - tag: arch
                op: "="
                value: "X86_64"
              - tag: memory
                op: ">="
                value: "1000"
```

After executing the 'linchpin -v up', the inventory result file just contains the first host name. In fact, two machines have been reserved according to the beaker url.

```
[example]
intel-3323-xxx.englab.nay.redhat.com hostname=intel-3323-xxx.englab.nay.redhat.com

[all]
intel-3323-xxx.englab.nay.redhat.com hostname=intel-3323-xxx.englab.nay.redhat.com
```

Note: 
My PinFile and layout files are shown as follows:

```
---
beaker:
  topology: test-rhel7.yml
  layout: test-layout.yml
  hooks:
    postup:
      - type: ansible
        name: test
        context: True
        actions:
          - playbook: ans_test_7.yml
            extra_vars: {"ansible_ssh_private_key_file": "/path/to/key"}

---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    example-node:
      count: 2
      host_groups:
        - example
```
