### ISSUE TITLE
bkr topology: Introduce support for 'repos' and 'packages' field in bkr topology file

### ISSUE THREAD

**Issue by yashkmankad** [CentOS-PaaS-SIG/linchpin#651]
The Beaker (bkr) provider for linchpin currently does not support adding additional repositories after provisioning using the 'repos' parameter and later installing packages using the 'package' or 'install' parameter. 

Example beaker topology file with 'repos' and 'package/install' would look like:

```yaml
---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: your-beaker-group
    recipesets:
      - family: Fedora28
        tag: RELEASED
        arch: x86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        count: 1
   repos:
      - name: "epel7"
        mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
      - name: "avocado"
        baseurl: "https://avocado-project.org/data/repos/avocado-fedora.repo"
   packages(/install):
      - yum(/dnf):  PyYAML tcpdump genisoimage fakeroot python-requests wget gdb gcc
```

Related documentation about using the repos and package/install options with the Beaker (bkr) command line tool:
 * https://beaker-project.org/docs/man/bkr.html#cmdoption-bkr-repo
 * https://beaker-project.org/docs/man/bkr.html#cmdoption-bkr-install

This issue is related to https://github.com/CentOS-PaaS-SIG/linchpin/issues/612, which was recently fixed and closed.

Thanks!
