### ISSUE TITLE
inventory file won't be generated before the hook task execute

### ISSUE THREAD

**Issue by shi2wei3** [CentOS-PaaS-SIG/linchpin#652]
v1.6.0b1 changed the way to generate inventory file in v1.5.5a16, which used to be a task "inventory_gen".
The result is my postup task won't get the inventory file and lead to failed to find any hosts to run it.

**Comment by shi2wei3** [comment]
```
# linchpin --version                                                                                                                                                         
linchpin version 1.6.0b1
```

Pinfile:
```
---                                                                                                                                                                                                                
beaker:
  topology: beaker-topology.yml
  layout: beaker-layout.yml
  hooks:
    postup:
        - name: test
          type: ansible
          context: True
          actions:
            - playbook: test.yaml
        - name: rhel-guest-image
          type: ansible
          context: True
          actions:
            - playbook: rhel-guest-image.yaml
              extra_vars: { 'ansible_ssh_private_key_file': '/root/workspaces/common/hooks/ansible/rhel-guest-image/xen-jenkins.pem'}
```

beaker-topology.yml
```
---                                                                                                                                                                                                                
topology_name: beaker_x64_rhel7
resource_groups:
  - resource_group_name: beaker_x64_rhel7
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        whiteboard: Provisioned with linchpin for rhel-guest-image
        job_group: xen-ci
        max_attempts: 240
        attempt_wait_time: 60
        cancel_message: Job cancelled by linchpin
        recipesets:
          - distro: RHEL-7.5-updates-20180813.0
            arch: x86_64
            variant: Server
            count: 1
            name: rhel7_x64
            hostrequires:
              - tag: hypervisor
                op: "="
                value: ""
              - tag: hostlabcontroller
                op: "="
                value: "lab-02.rhts.eng.bos.redhat.com"
```

beaker-layout.yml
```
---                                                                                                                                                                                                                
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    x64-node:
      count: 1
      host_groups:
        - x86_64
```

Outputs:
```
...
...
...
TASK [gather_resources : set topology_name] ************************************************************************************************************************************************************************
task path: /root/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:60
ok: [localhost] => {
    "ansible_facts": {
        "topology_name": "beaker_x64_rhel7"
    },
    "changed": false
}

TASK [gather_resources : Updating uhash-based inventory_path with the absolute path] *******************************************************************************************************************************
task path: /root/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:64
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [gather_resources : Updating inventory_path with the absolute path] *******************************************************************************************************************************************
task path: /root/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:70
ok: [localhost] => {
    "ansible_facts": {
        "inventory_path": "/root/workspaces/x64_rhel7/inventories/beaker_x64_rhel7.inventory"
    },
    "changed": false
}

TASK [gather_resources : Add inventory_path to outputs] ************************************************************************************************************************************************************
task path: /root/linchpin/lib/python2.7/site-packages/linchpin/provision/roles/gather_resources/tasks/main.yml:76
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "action": "up",
            "conn_str": "/root/workspaces/x64_rhel7/.rundb/rundb-274973440639315.json",
            "db_type": "TinyRunDB",
            "key": "outputs",
            "operation": "update",
            "run_id": 2,
            "table": "beaker",
            "value": "[{'inventory_path': ['/root/workspaces/x64_rhel7/inventories/beaker_x64_rhel7.inventory']}]"
        }
    },
    "output": 2
}

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=30   changed=5    unreachable=0    failed=0

Action 'up' on Target 'beaker' is complete
hook postinv initiated
hook postup initiated
running postup hooks
-------
start hook ansible:test
 [WARNING]: Unable to parse /root/workspaces/x64_rhel7/inventories/beaker_x64_rhel7.inventory as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

Loading callback plugin unnamed of type old, v1.0 from /root/linchpin/lib/python2.7/site-packages/linchpin/callbacks.pyc
Loading callback plugin default of type stdout, v2.0 from /root/linchpin/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yaml ************************************************************************************************************************************************************************************************

PLAY [test] ********************************************************************************************************************************************************************************************************

TASK [test] ********************************************************************************************************************************************************************************************************
task path: /root/workspaces/x64_rhel7/hooks/ansible/test/test.yaml:5
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "checksum_algorithm": "sha1",
            "follow": false,
            "get_attributes": true,
            "get_checksum": true,
            "get_md5": null,
            "get_mime": true,
            "path": "/root/workspaces/x64_rhel7/inventories/beaker_x64_rhel7.inventory"
        }
    },
    "stat": {
        "exists": false
    }
}

TASK [test] ********************************************************************************************************************************************************************************************************
task path: /root/workspaces/x64_rhel7/hooks/ansible/test/test.yaml:10
skipping: [localhost] => {}

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

end hook ansible:test
-------
-------
start hook ansible:rhel-guest-image
Loading callback plugin unnamed of type old, v1.0 from /root/linchpin/lib/python2.7/site-packages/linchpin/callbacks.pyc
Loading callback plugin default of type stdout, v2.0 from /root/linchpin/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: rhel-guest-image.yaml ************************************************************************************************************************************************************************************

PLAY [rhel-guest-image] ********************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************************************************************************************************************************************************

end hook ansible:rhel-guest-image
-------

ID: 2
Action: up

Target                  Run ID  uHash   Exit Code
-------------------------------------------------
beaker                       2  b55d70          0

```

What i expect is my "postup" ansible playbooks would be able to find the inventory hosts which used to work in v1.5.5a16, i don't know why TASK inventory_gen doesn't triggered, is there anything wrong in my configurations?
