### ISSUE TITLE
LinchPin v1.5.4 breaks when parsing JSON for a hook using ansible-playbook extra vars

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#659]
## Overview
I structured my Cinch code for LinchPin 1.5.3 around the ansible post-up hook.
I started seeing strange behavior later on, but I didn't associate this with the 1.5.4 release until much later.
It seems that whatever was parsing the template data has changed in some capacity, and no longer accepts a string of formatted JSON. My own code was more complex, and I suspect that this somehow masked the underlying issue. You can reproduce the issue for yourself using the files below.

## The Error Message
start hook ansible:test
Invalid syntax: {'actions': [{0: [{'extra_vars': ['must be of dict type']}]}]}

## How to Reproduce
I've listed the files I used to reproduce the error below. This will fail with the error above on LinchPin 1.5.4, but not on LinchPin 1.5.1 through 1.5.3. I suspect it would work on 1.5.0, but for me that executable fails because of a broken config path to the linchpin log. 

PinFile
```
---
jenkins-slave:
  topology:
    topology_name: jenkins-slave
    resource_groups:
    - resource_group_name: dummy-slaves
      resource_group_type: dummy
      resource_definitions:
      - role: dummy_node
        name: dummy-node
        count: 1
  layout:
    inventory_layout:
      hosts:
        jenkins-slave:
          count: 1
          host_groups:
            - rhel7
            - certificate_authority
            - repositories
            - jenkins_slave
            - master_node
  hooks:
    postup:
    - type: ansible
      name: "test"
      context: True
      actions:
      - playbook: site.yml
        extra_vars: {{ extra_vars }}
```

Post Up Playbook
hooks/ansible/test/site.yml
```
---
- hosts: localhost
  tasks:
  - debug:
    name: "Test Variable"
    msg: "{{ test }}"
```

LinchPin Command
```
linchpin -vvv --template-data '{"extra_vars":{"test":"Hello World"}}' -p PinFile up
```
