### ISSUE TITLE
Openshift provider support credentials file

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#675]
Openshift currently support inline credentials:

```
---
# http://<route_name>-<name_space>.cloud.<end_point>
topology_name: simple
resource_groups:
  - resource_group_name: simple
    resource_group_type: openshift
    resource_definitions:
    ....
    credentials:
      api_endpoint: paas.lab.upshift.redhat.com
      api_token: secrettokenhere
```
It should support the auth_drive, and able to process such topology:

```
---
# http://<route_name>-<name_space>.cloud.<end_point>
topology_name: simple
resource_groups:
  - resource_group_name: simple
    resource_group_type: openshift
    resource_definitions:
    ....
    credentials:
      filename: oc_creds.yml
      profile: default
```
