### ISSUE TITLE
Resultant inventory are not well generated on Libvirt provider

### ISSUE THREAD

**Issue by jparrill** [CentOS-PaaS-SIG/linchpin#681]
Hi there,

There is an error on the Ansible Inventory generation on libvirt provider when you have more than 1 node into a group. With this setup you could replicate the error:

- ocp-libvirt-topology.yml
```yaml
---
topology_name: "libvirt-ocp"
resource_groups:
  - resource_group_name: "ocp-masters"
    resource_group_type: "libvirt"
    resource_definitions:
      - role: libvirt_node
        name: ocp-master
        uri: qemu:///system
        count: 1
        image_src: CentOS-7-x86_64-GenericCloud.qcow2
        memory: 1024
        vcpus: 1
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default
        additional_storage: 10G
        cloud_config:
          users:
            - name: jparrill
              gecos: Juan Manuel
              groups: wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_import_id: gh:jparrill
              lock_passwd: true
  - resource_group_name: "ocp-nodes"
    resource_group_type: "libvirt"
    resource_definitions:
      - role: libvirt_node
        name: ocp-node
        uri: qemu:///system
        count: 3
        image_src: CentOS-7-x86_64-GenericCloud.qcow2
        memory: 1024
        vcpus: 1
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default
        additional_storage: 10G
        cloud_config:
          users:
            - name: jparrill
              gecos: Juan Manuel
              groups: wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_import_id: gh:jparrill
              lock_passwd: true
```

- ocp-layout.yml
```yaml
---
inventory_layout:
    inventory_file: "{% raw -%}{{ workspace }}/inventories/libvirt-ocp-{{ uhash }}.inventory{%- endraw %}"
    vars:
        hostname: __IP__
    hosts:
        master:
            count: 1
            host_groups:
            - masters
        node:
            count: 3
            host_groups:
            - nodes
    host_groups:
        all:
            vars:
                ansible_user: jparrill
```

- Pinfile
```
---
libvirt-ocp:
  topology: ocp-libvirt-topology.yml
  layout: ocp-layout.yml
  hooks:
    postup:
      - type: ansible
        name: ping
        context: True
        actions:
          - playbook: ping.yaml
            extra_vars: { "ansible_ssh_private_key_file": "~/.ssh/id_rsa" }
    preup:
      - type: shell
        name: Pre-Up Step
        actions:
          - echo Pre-up Step Message
    predestroy:
      - type: shell
        name: Pre-destroy Step
        actions:
          - echo Pre-destroy Step Message
    postdestroy:
      - type: shell
        name: Post-destroy Step
        actions:
          - echo Post-destroy Step Message
```

The resultant invetory is:

```
[all:vars]
ansible_user = jparrill

[masters]
192.168.122.210 hostname=192.168.122.210

[nodes]
192.168.122.122 hostname=192.168.122.122

[all]
192.168.122.210 hostname=192.168.122.210
192.168.122.122 hostname=192.168.122.122
```

when should be something like:
```
[all:vars]
ansible_user = jparrill

[masters]
192.168.122.210 hostname=192.168.122.210

[nodes]
192.168.122.122 hostname=192.168.122.122
192.168.122.123 hostname=192.168.122.123
192.168.122.124 hostname=192.168.122.124

[all]
192.168.122.210 hostname=192.168.122.210
192.168.122.122 hostname=192.168.122.122
192.168.122.123 hostname=192.168.122.123
192.168.122.124 hostname=192.168.122.124
```

Talking with @samvarankashyap through IRC seems a weird bug just only on the Libvirt provider, dummy one is working fine.

**Comment by jparrill** [comment]
UPDATE:

Putting the same name on the "resource_group_name" from topology file, on both resources, in this case, Masters and Nodes, seems to work.

```yaml
---
topology_name: "libvirt-ocp"
resource_groups:
  - resource_group_name: "ocp-lab"
    resource_group_type: "libvirt"
    resource_definitions:
      - role: libvirt_node
        name: ocp-master
        uri: qemu:///system
        count: 1
        image_src: CentOS-7-x86_64-GenericCloud.qcow2
        memory: 1024
        vcpus: 1
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default
        additional_storage: 10G
        cloud_config:
          users:
            - name: jparrill
              gecos: Juan Manuel
              groups: wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_import_id: gh:jparrill
              lock_passwd: true
  - resource_group_name: "ocp-lab"
    resource_group_type: "libvirt"
    resource_definitions:
      - role: libvirt_node
        name: ocp-node
        uri: qemu:///system
        count: 3
        image_src: CentOS-7-x86_64-GenericCloud.qcow2
        memory: 1024
        vcpus: 1
        arch: x86_64
        ssh_key: id_rsa
        networks:
          - name: default
        additional_storage: 10G
        cloud_config:
          users:
            - name: jparrill
              gecos: Juan Manuel
              groups: wheel
              sudo: ALL=(ALL) NOPASSWD:ALL
              ssh_import_id: gh:jparrill
              lock_passwd: true
```

This is the resultant inv:

```
[all:vars]
ansible_user = jparrill

[masters]
192.168.122.194 hostname=192.168.122.194

[nodes]
192.168.122.177 hostname=192.168.122.177
192.168.122.99 hostname=192.168.122.99
192.168.122.156 hostname=192.168.122.156

[all]
192.168.122.194 hostname=192.168.122.194
192.168.122.177 hostname=192.168.122.177
192.168.122.99 hostname=192.168.122.99
192.168.122.156 hostname=192.168.122.156
```

**Comment by samvarankashyap** [comment]
@jparrill I used the following topology it works fine, i think its problem with the naming somehow . 
```
---
beaker-openstack:
  topology:
    topology_name: beaker-openstack
    resource_groups:
      - resource_group_name: libvirt-new-master
        resource_group_type: libvirt
        resource_definitions:
        - role: libvirt_node
          name: centos71_master
          uri: qemu:///system
          count: 1
          image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz
          #image_src: file:///home/srallaba/workspace/lp_ws/virt_customize/playbooks/virt_customize_images/centos7.qcow2
          memory: 1024
          vcpus: 1
          arch: x86_64
          networks:
          - name: default
      - resource_group_name: libvirt-new-nodes
        resource_group_type: libvirt
        resource_definitions:
        - role: libvirt_node
          name: centos71
          uri: qemu:///system
          count: 2
          image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1608.qcow2.xz
          #image_src: file:///home/srallaba/workspace/lp_ws/virt_customize/playbooks/virt_customize_images/centos7.qcow2
          memory: 1024
          vcpus: 1
          arch: x86_64
          networks:
          - name: default
  layout:
    inventory_layout:
      vars:
        hostname: __IP__
      hosts:
        masters:
          count: 1
          host_groups:
            - masters
        nodes:
          count: 2
          host_groups:
            - nodes
      host_groups:
        all:
          vars:
            ansible_python_interpreter: /usr/bin/python3
            ansible_user: root
            ansible_ssh_common_args: -o StrictHostKeyChecking=no

# inventory generated:

[all:vars]
ansible_ssh_common_args = -o StrictHostKeyChecking=no
ansible_python_interpreter = /usr/bin/python3
ansible_user = root

[masters]
192.168.122.238 hostname=192.168.122.238

[nodes]
192.168.122.164 hostname=192.168.122.164
192.168.122.181 hostname=192.168.122.181

[all]
192.168.122.238 hostname=192.168.122.238
192.168.122.164 hostname=192.168.122.164
192.168.122.181 hostname=192.168.122.181


```
