### ISSUE TITLE
Beaker jobs are not cancelled in teardown with --tx-id

### ISSUE THREAD

**Issue by jaypoulz** [CentOS-PaaS-SIG/linchpin#707]
## Overview
It appears as though there is an issue with linchpin teardown not cancelling beaker jobs in the case of beaker resource teardown. At the moment, I've been testing this in 2 different environments, and behavior is slightly different in both, but both fail whenever `--tx-id` is passed.

For context, I've been using the default LinchPin config for 1.6.2, so `use_rundb_for_actions = True` should be set by default. On my local machine, I have it explicitly set it `~/.config/linchpin/linchpin.conf` and I have observed the same behavior.

These commands fail on all of my environments.
```
linchpin --workspace provisioning/workspace --verbose destroy beaker-slave --tx-id 1
linchpin --workspace provisioning/workspace --verbose destroy --tx-id 1
```
This command works on my local host, but not on my production environment. The latter may be related or a different issue altogether.
```
linchpin --workspace provisioning/workspace --verbose destroy beaker-slave
```
## Sample Run Output
This sample output has been gathered from my local host.
[LinchPin Up](http://pastebin.test.redhat.com/651467)
[LinchPin Down (Failed)](http://pastebin.test.redhat.com/651464)
[LinchPin Journal](http://pastebin.test.redhat.com/651465)
[Linchpin Down (Success)](http://pastebin.test.redhat.com/651468)

## Files
```
PinFile
---
jenkins-slave:
  topology:
    topology_name: jenkins-slave
    resource_groups:
    - resource_group_name: dummy-slaves
      resource_group_type: dummy
      resource_definitions:
      - role: dummy_node
        name: dummy-node
        count: 1
  layout:
    inventory_layout:
      hosts:
        jenkins-slave:
          count: 1
          host_groups:
            - rhel7
            - certificate_authority
            - repositories
            - jenkins_slave
            - master_node
  hooks:
    postup:
    - type: ansible
      name: "test"
      context: True
      actions:
      - playbook: site.yml
        extra_vars: {{ extra_vars }}
beaker-slave:
  topology:
    topology_name: beaker-slave
    resource_groups:
    - resource_group_name: beaker-slaves
      resource_group_type: beaker
      resource_definitions:
      - role: bkr_server
        job_group: 'multiarch-qe'
        whiteboard: "test slave for multiarch testing"
        max_attempts: 180
        attempt_wait_time: 60
        cancel_message: Beaker request timeout
        recipesets:
        - distro: "RHEL-ALT-7.5"
          arch: x86_64
          variant: Server
          count: 1
          name: "Beaker Slave"
  layout:
    inventory_layout:
      hosts:
        jenkins-slave:
          count: 1
        beaker-slave:
          count: 1
  hooks:
    postup:
    - type: ansible
      name: "test"
      context: True
      actions:
      - playbook: site.yml
        extra_vars: {{ extra_vars }}
```
