### ISSUE TITLE
teardown_resource_group.yml : linchpin destroy does not end beaker reservation as it always defaults to [ ]. 

### ISSUE THREAD

**Issue by yashkmankad** [CentOS-PaaS-SIG/linchpin#717]
We are using linchpin to create a beaker recipe that would reserve the system for 24 hours if our CI jobs complete unsuccessfully (FAIL or UNSTABLE). However, if a job completes with a SUCCESS, we use the linchpin destroy command, to end the reservation and return the system to the beaker pool. 

However, we have noticed that our beaker recipes continue to hold systems from 24 hours even if  job completes SUCCESSfully. Oksana (GH @anascko) identified the following lines as being the issue -- 

https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/provision/roles/beaker/tasks/teardown_resource_group.yml#L48-L53

The task "build job_id list" will always return a list of empty job_ids [ ], because it has a 'default([])' set in the with_items. It uses an incorrect iteration of "topo_output_resources['beaker_res']". It should only use the list with_items: "{{ topo_output_resources }}"

@samvarankashyap  @p3ck 

Could you kindly have a look and address this issue ? Thanks.

**Comment by herlo** [comment]
@yashkmankad thank you for filing this issue. To help us troubleshoot this problem, could you provide the following information. 

* A valid PinFile, with a full topology example
* The full output from the linchpin up and destroy command using the `-vvvv` option.
* A copy of your effective `linchpin.conf`, specifically noting
  * generate_resources
  * use_rundb_for_actions

This data will help us troubleshoot more quickly. Thanks!

**Comment by herlo** [comment]
@anascko it doesn't appear as though your attachment came through. If you like, I can recommend https://gist.github.com/ as a good place to link to where the files won't go away after posting. A link can then be provided here.

**Comment by anascko** [comment]
Sorry, I thought that I can download archive
https://gist.github.com/anascko/e8d294b50b8b2f21ee0f2a2613bc8385
http://etherpad.corp.redhat.com/ep/pad/view/ro.fL27XxNJDWJ/latest
http://etherpad.corp.redhat.com/ep/pad/view/ro.mbLwGJ4YuN7/latest

**Comment by yashkmankad** [comment]
@herlo , Sorry for the delay, here are the requested files --
 
PinFile               : https://gist.github.com/yashkmankad/cd455349733204314a3c208254e96ac0
topology            : https://gist.github.com/yashkmankad/55a3b4ccc91d37d6ac76004bb8546b73
linchpin up         : https://gist.github.com/yashkmankad/3d4f269841256a19030138ebcd880bfb
linchpin destroy : https://gist.github.com/yashkmankad/d362991393792277a84cbff97aefc7b1
linchpin conf      : https://gist.github.com/yashkmankad/f6d4ecd375aaead62aa54c55b6f7976d

**Comment by p3ck** [comment]
I'm not able to use the topology file you provided.  It does not validate with the latest linchpin.  I made some changes to have it match the newer format and it works as expected for me.  Both up and destroy.  What version of linchpin are you using?

Here is the modified version of the topology.
```yaml
---
topology_name: "rhel75-x86_64"
resource_groups:
  - resource_group_name: "rhel75-x86_64"
    resource_group_type: beaker
    resource_definitions:
      - role: bkr_server
        whiteboard: Recreate Issue
        max_attempts: 180
        attempt_wait_time: 60
        recipesets:
          - distro: RHEL-7.5
            arch: x86_64
            variant: Server
            name: Foo
            count: 1
            hostrequires:
              - tag: arch
                op: "="
                value: "x86_64"
              - tag: memory
                op: ">="
                value: 8000
              - rawxml: "<key_value key='HVM' op='=' value='1'/>"
            repos:
              - baseurl: http://mirrors.mit.edu/epel/7/$basearch
            install:
              - yum-utils wget git python-devel cryptsetup gcc
```
