### ISSUE TITLE
change in instance name for openstack with linchpin 1.6.3

### ISSUE THREAD

**Issue by bhavikbhavsar** [CentOS-PaaS-SIG/linchpin#737]
In linchpin version 1.0.4 that we were using,
the openstack instance name would form based on below tasks in provision_os_server.yml

```
- name: "provisioning os_server resources"
  os_server2:
    state: "{{ state }}"
    name: "{{ res_grp_name }}_{{ res_def['res_name'] | default(res_def['name']) }}"
```

This seems to have changed in latest version 1.6.3

```
 name: "provision/teardown os_server resources with provided auth"
  os_server:
    state: "{{ state }}"
    auth: "{{ auth_var }}"
    name: "{{ prov_inst }}"

```
So now when instance is provisioned with latest version 1.6.3

For topo file as below:

```
resource_groups:
- credentials:
    filename: clouds.yaml
    profile: devstack
  resource_definitions:
  - count: 1
    fip_pool: 10.8.240.0
    flavor: m1.large
    image: rhel-7.5
    keypair: idm-jenkins
    name: master
    networks:
    - idm-jenkins
    type: os_server
  resource_group_name: linchpin_768
  resource_group_type: openstack
topology_name: openstack_topo
```
The instance name it assigns is `master1`  which was before `linchpin_768_master1`.

Is there any specific reason for this change?

My use case:
I had an working automation for my ci to provision instances with different name each time it runs `linchpin up` to automatically append 3 digit random number to the resource_group_name.
