### ISSUE TITLE
Inventory grouping wrong when installs fail

### ISSUE THREAD

**Issue by johnbieren** [CentOS-PaaS-SIG/linchpin#796]
Say you have four hosts being provisioned with a layout like below:
```
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    beaker-fedora-node:
      count: 1
      host_groups:
        - root-user-layout
        - fedora-hosts
    beaker-centos-node:
      count: 1
      host_groups:
        - root-user-layout
        - centos-hosts
    openstack-fedora-node:
      count: 1
      host_groups:
        - fedora-user-layout
        - fedora-hosts
    openstack-centos-node:
      count: 1
      host_groups:
        - centos-user-layout
        - centos-hosts
  host_groups:
    all:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
    root-user-layout:
      vars:
        ansible_user: root
    fedora-user-layout:
      vars:
        ansible_user: fedora
    centos-user-layout:
      vars:
        ansible_user: centos
```
When all four installs work, everything is as expected in the resulting inventory. However, say the beaker-centos installation fails. The resulting inventory simply skips over the beaker-centos host and continues popping. So, the next host, openstack-fedora, gets the beaker-centos host vars and the fourth host, openstack-centos, gets the third host vars, openstack-fedora. I should note that the run completed successfully as well, despite a beaker host install failing. My run "passed," but I had three hosts instead of four and all hosts x+1 where x is the host install that failed had their variables offset by 1, rendering the inventory unusable. This is consistent whenever one of the installs fails (but again, when all four installs work the inventory is exactly as specified and works great).
