### ISSUE TITLE
RFE: Beaker support for kickstart

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#880]
Beaker allows kickstart to be written within the recipe element, this can allow simpler inline (PinFile) customization of deployments, and with [Jinja include|http://jinja.pocoo.org/docs/2.10/templates/#include| it could be reused. For example:
Pinfile:
```yaml
---
simple:
  topology:
    topology_name: simple
    resource_groups:
      - resource_group_name: simple
        resource_group_type: beaker
        resource_definitions:
          - role: bkr_server
            recipesets:
              - distro: RHEL-6.5
                arch: x86_64
                count: 1
                name: rhel65
                kickstart: |
{% macro kickstart() %}{% include 'kickstart' -%}{%- endmacro -%}
                {{ kickstart() | indent(18, True) }}
```
result:
```xml
<job id="3262259" owner="abraverm@redhat.com" result="New" status="Installing" retention_tag="scratch">
  <whiteboard>Provisioned by LinchPin</whiteboard>
  <recipeSet priority="Normal" response="ack" id="5160991">
    <recipe id="6347265" job_id="3262259" recipe_set_id="5160991" whiteboard="" role="None" kickstart_url="http://beaker.engineering.redhat.com/kickstart/5031795" ks_meta="method=nfs" kernel_options="" kernel_options_post="" start_time="2018-12-26 11:37:06" result="New" status="Installing" distro="RHEL-6.5" arch="x86_64" family="RedHatEnterpriseLinux6" variant="Client" system="lenovo-rd230-02.khw.lab.eng.bos.redhat.com">
      <autopick random="false" />
      <watchdog />
      <installation />
      <packages />
      <ks_appends />
      <roles>
        <role value="None">
          <system value="lenovo-rd230-02.khw.lab.eng.bos.redhat.com" />
        </role>
      </roles>
      <repos />
      <distroRequires>
        <and>
          <distro_name op="=" value="RHEL-6.5" />
          <distro_arch op="=" value="x86_64" />
        </and>
      </distroRequires>
      <hostRequires>
        <system_type value="Machine" />
      </hostRequires>
      <partitions />
      <logs>
        <log href="https://beaker.engineering.redhat.com/recipes/6347265/logs/console.log" name="console.log" />
      </logs>
      <task name="/distribution/dummy" role="STANDALONE" version="1.0-0" id="86228168" result="New" status="Waiting" avg_time="300">
        <rpm name="rh-tests-distribution-dummy" path="/mnt/tests/distribution/dummy" />
        <roles>
          <role value="STANDALONE">
            <system value="lenovo-rd230-02.khw.lab.eng.bos.redhat.com" />
          </role>
        </roles>
        <logs />
      </task>
      <task name="/distribution/reservesys" role="STANDALONE" version="3.4-10" id="86228169" result="New" status="Waiting" avg_time="86400">
        <rpm name="beaker-distribution-reservesys" path="/mnt/tests/distribution/reservesys" />
        <roles>
          <role value="STANDALONE">
            <system value="lenovo-rd230-02.khw.lab.eng.bos.redhat.com" />
          </role>
        </roles>
        <logs />
      </task>
      <kickstart>install
  key --skip
  lang en_US.UTF-8
  skipx
  keyboard us
  network --device eth0 --bootproto dhcp
  rootpw --plaintext testingpassword
  firewall --disabled
  authconfig --enableshadow --enablemd5
  selinux --permissive
  timezone --utc Europe/Prague

  bootloader --location=mbr --driveorder=sda,sdb
# Clear the Master Boot Record
  zerombr
# Partition clearing information
  clearpart --all --initlabel
# Disk partitioning information
  part /RHTSspareLUN1 --fstype=ext3 --size=20480 --asprimary --label=sda_20GB --ondisk=sda
  part /RHTSspareLUN2 --fstype=ext3 --size=1 --grow --asprimary --label=sda_rest --ondisk=sda
  part /boot --fstype=ext3 --size=200 --asprimary --label=BOOT --ondisk=sdb
# part swap --fstype=swap --size=512  --asprimary --label=SWAP_007 --ondisk=sdb
  part / --fstype=ext3 --size=1 --grow --asprimary --label=ROOT  --ondisk=sdb

  reboot

  %packages --excludedocs --ignoremissing --nobase</kickstart>
    </recipe>
  </recipeSet>
</job>
```
