### ISSUE TITLE
Shell hook context should be prefix to the command

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#882]
When shell hook is defined and context is passed, the variables are set after the command and not before it. For example:
```yaml
hooks:
  postup:
    - name: my command
      type: shell
      context: true
      actions:
        - 'somecommand --option1'
```
Linchpin will try to run `somecommand --option1 inventory=...`  and sometimes will fail because the command will assume the args are for it to process. What it should do is `inventory=.... somecommand --option1`, that way all that comes before it is environment variable. So the user can even do something like `somecommand --option1 $inventory`
