### ISSUE TITLE
Doc: Action managers documentation

### ISSUE THREAD

**Issue by abraverm** [CentOS-PaaS-SIG/linchpin#883]
Action managers have different action syntax and handle context differently. The details are covered partially inline but should be available in the general documentation. For example [Ansible][https://github.com/CentOS-PaaS-SIG/linchpin/blob/develop/linchpin/hooks/action_managers/ansible_action_manager.py] action syntax is:
```yaml
- playbook: playbook_file
  vars: vars_file
  extra_vars: '{}'
```
While for shell, the action is simply strings.
