### ISSUE TITLE
(8) Linchpin cli list , get to fetch from remote repositories

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linchpin#92]
Currently linchpin cli when passed with argument list fetches , the topologies and layouts from local packaged folder . 
As an enhancement , we would like linchpin cli to fetch from remote repository . Remote can be an external server or a github repository

Proposed usage would be as follows:
linchpin list --remote <url> --topos
linchpin list --remote <url> --layouts
linchpin get --remote <url> --topos
linchpin get --remote <url> --layouts
# used to set the remote url
linchpin config set --remote <url>

**Comment by herlo** [comment]
A better approach here might be to think in terms of the topologies and layouts. Something like:

```
linchpin topology create|get|list
linchpin layout create|get|list
```

In terms of `linchpin topology get`, it seems having a --remote option is not needed. Consider that anything with file:// would imply local (or just with a /path/to/topo), whereas http://, git://, ssh:// would imply remote protocols. 

Also, it might be advantageous to have a component in the Pinfile which identifies the remote registry as indicated previously in PR #88. Something like:

```
topology_registry: git://github.com/CentOS-PaaS-SIG/linchpin_topologies.git
layout_registry: git://github.com/CentOS-PaaS-SIG/linchpin_layouts.git

across2clouds:
 topology_name: openshift_aws_5node
 inventory_layout_file: openshift_layout_with_5nodes

dockercontainer:
 topology: herlo_docker_stuff
```

If this were in place, one could provide the command:

```
linchpin topology get openshift_aws_5node
```

which would look at the topology registry and pull down the given topology and put it in the proper place (probably the `topologies` directory at PWD). Additionally, one could override the config file by passing `--topology_registry=file://path/to/local/registry`.

Configuring like this could also allow for push actions, given a file://, git@, or ssh:// location.
