### ISSUE TITLE
Host Groups Wrong in Inventory

### ISSUE THREAD

**Issue by johnbieren** [CentOS-PaaS-SIG/linchpin#936]
Using a layout like this:
```
---
inventory_layout:
  vars:
    hostname: __IP__
  hosts:
    beaker-fedora-node:
      count: 1
      host_groups:
        - root-user-layout
        - fedora-hosts
    beaker-centos-node:
      count: 1
      host_groups:
        - root-user-layout
        - centos-hosts
    openstack-fedora-node:
      count: 1
      host_groups:
        - fedora-user-layout
        - fedora-hosts
    openstack-centos-node:
      count: 1
      host_groups:
        - centos-user-layout
        - centos-hosts
  host_groups:
    all:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: -o StrictHostKeyChecking=no
    root-user-layout:
      vars:
        ansible_user: root
    fedora-user-layout:
      vars:
        ansible_user: fedora
    centos-user-layout:
      vars:
        ansible_user: centos
```
I am getting back an inventory with two hosts in centos-hosts, two hosts in fedora-hosts, two hosts in root hosts, and one in each of fedora-user and centos-user, as expected, but the hosts contained in each group are wrong. A centos host is in the fedora host group and vice versa, the centos-user host is not actually a centos host, etc.
