### ISSUE TITLE
RFE: implement virtualbmc support for libvirt VMs

### ISSUE THREAD

**Issue by mcornea** [CentOS-PaaS-SIG/linchpin#938]
Simulating baremetal ipmi for virtual machines requires support for creating virtulabmc's for libvirt VMs after the provisioning has finished.  We already have the setup logic inside an ansible role[1] but we need help to integrate it into linchpin.

[1] https://github.com/redhat-openstack/infrared/tree/master/infrared/common/roles/vbmc

**Comment by mcornea** [comment]
Please let me know if you consider this should be something part of the libvirt provider or we should keep it as a separate standalone role outside linchpin. Thanks!

**Comment by samvarankashyap** [comment]
@mcornea I would say adding a external/internal hook to linchpin would suffice the requirement . 
@p3ck any thoughts ?

**Comment by p3ck** [comment]
@samvarankashyap yes, I was hoping this could be done via a hook that they could put in their pinfile.  Can you confirm they would have access to the hypervisor from the hook?  I'm pretty sure that the playbook needs to run on the hypervisor and not on the just provisioned libvirt machines.

**Comment by samvarankashyap** [comment]
@p3ck : I see two cases here : 
1. If linchpin runs on hypervisor the hook(playbooks) can carryout a localaction using sudo/become permissions
2. If linchpin runs on a external machine connecting to libvirt hypervisor then yes it needs access

**Comment by samvarankashyap** [comment]
@mcornea @abraverm Any update on the this issue ?

**Comment by abraverm** [comment]
I think we agreed on hooks, @mcornea correct?

**Comment by mcornea** [comment]
> I think we agreed on hooks, @mcornea correct?

Yes, that's right.

**Comment by JunqiZhang0** [comment]
@mcornea Hey is there any sample inventory_file I can use for the vbmc role?

**Comment by 14rcole** [comment]
@abraverm didn't you do something with vbmc at some point?

**Comment by JunqiZhang0** [comment]
@14rcole I'm trying to integrate the Ansible role into linchpin, but the role didn't work that well on my end

**Comment by abraverm** [comment]
@14rcole unfortunately no.

**Comment by mcornea** [comment]
> @mcornea Hey is there any sample inventory_file I can use for the vbmc role?

Hey. I'll paste below the Pinfile and resulting inventory file. I also put the exact role code that we're currently using in a post deploy hook in https://github.com/mcornea/ansible-vbmc-role

```yaml
---
# If provisionhost_hostname is not set then assume it's a virtual environment
libvirt-network:
  topology:
    topology_name: "libvirt_network"
    resource_groups:
      - resource_group_name: baremetal_net
        resource_group_type: libvirt
        resource_definitions:
          - name: baremetal
            role: libvirt_network
            uri: qemu:///system
            forward_mode: nat
            ip: 192.168.123.1
            dhcp_start: 192.168.123.100
            dhcp_end: 192.168.123.150
            delete_on_destroy: yes
            domain: rhhi-virt-cluster.qe.lab.redhat.com
            bridge: baremetal
            dns:
              forwarders:
                - domain: apps.rhhi-virt-cluster.qe.lab.redhat.com
                  addr: 127.0.0.1
              hosts:
                - ip: 192.168.123.5
                  hostnames:
                    - api
                - ip: 192.168.123.6
                  hostnames:
                    - ns1

      - resource_group_name: provisioning_net
        resource_group_type: libvirt
        resource_definitions:
          - name: provisioning
            role: libvirt_network
            uri: qemu:///system
            bridge: provisioning
            delete_on_destroy: yes

  hooks:
    predestroy:
      - name: rhhi-setup
        type: ansible
        context: True
        actions:
          - playbook: requirements.yaml

cfgs:
  libvirt:
    __IP__: name
    __ADDRESS__: ip

libvirt-new:
  topology:
    topology_name: rhhi
    resource_groups:
      - resource_group_name: rhhi-node-master
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: rhhi-node-master
            uri: qemu:///system
            count: 3
            image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
            memory: 16384
            vcpus: 8
            arch: x86_64
            ssh_key: id_rsa
            additional_storage: 42G
            disk_type: virtio_scsi
            name_separator: '-'
            networks:
              - name: baremetal
              - name: provisioning
                dhcp: false
            storage:
              - name: osd0
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdb
              - name: osd1
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdc
              - name: osd2
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdd
              - name: osd3
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sde
      - resource_group_name: rhhi-node-worker
        resource_group_type: libvirt
        resource_definitions:
          - role: libvirt_node
            name: rhhi-node-worker
            uri: qemu:///system
            count: 4
            image_src: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
            memory: 16384
            vcpus: 8
            arch: x86_64
            ssh_key: id_rsa
            additional_storage: 42G
            disk_type: virtio_scsi
            name_separator: '-'
            networks:
              - name: baremetal
              - name: provisioning
                dhcp: false
            storage:
              - name: osd0
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdb
              - name: osd1
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdc
              - name: osd2
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sdd
              - name: osd3
                size: 8
                cache: unsafe
                units: G
                disk_type: virtio_scsi
                device: sde

  layout:
    inventory_layout:
      vars:
        hostname: __IP__
        ansible_ssh_host: __ADDRESS__
        ansible_ssh_user: centos
        ansible_ssh_common_args: '"-o StrictHostKeyChecking=no"'
      hosts:
        master:
          count: 3
          host_groups:
            - master
            - openshift
        worker:
          count: 4
          host_groups:
            - worker
            - openshift
        openshift:
          count: 7
          host_groups:
            - openshift
```

```ini
[worker]
rhhi-node-worker-0 ansible_ssh_host=192.168.123.127 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-0 ansible_ssh_user=centos
rhhi-node-worker-1 ansible_ssh_host=192.168.123.104 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-1 ansible_ssh_user=centos
rhhi-node-worker-2 ansible_ssh_host=192.168.123.141 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-2 ansible_ssh_user=centos
rhhi-node-worker-3 ansible_ssh_host=192.168.123.133 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-3 ansible_ssh_user=centos

[master]
rhhi-node-master-0 ansible_ssh_host=192.168.123.140 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-0 ansible_ssh_user=centos
rhhi-node-master-1 ansible_ssh_host=192.168.123.120 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-1 ansible_ssh_user=centos
rhhi-node-master-2 ansible_ssh_host=192.168.123.116 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-2 ansible_ssh_user=centos

[openshift]
rhhi-node-master-0 ansible_ssh_host=192.168.123.140 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-0 ansible_ssh_user=centos
rhhi-node-master-1 ansible_ssh_host=192.168.123.120 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-1 ansible_ssh_user=centos
rhhi-node-master-2 ansible_ssh_host=192.168.123.116 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-2 ansible_ssh_user=centos
rhhi-node-worker-0 ansible_ssh_host=192.168.123.127 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-0 ansible_ssh_user=centos
rhhi-node-worker-1 ansible_ssh_host=192.168.123.104 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-1 ansible_ssh_user=centos
rhhi-node-worker-2 ansible_ssh_host=192.168.123.141 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-2 ansible_ssh_user=centos
rhhi-node-worker-3 ansible_ssh_host=192.168.123.133 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-3 ansible_ssh_user=centos

[all]
rhhi-node-worker-3 ansible_ssh_host=192.168.123.133 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-3 ansible_ssh_user=centos
rhhi-node-worker-2 ansible_ssh_host=192.168.123.141 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-2 ansible_ssh_user=centos
rhhi-node-worker-1 ansible_ssh_host=192.168.123.104 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-1 ansible_ssh_user=centos
rhhi-node-worker-0 ansible_ssh_host=192.168.123.127 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-worker-0 ansible_ssh_user=centos
rhhi-node-master-2 ansible_ssh_host=192.168.123.116 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-2 ansible_ssh_user=centos
rhhi-node-master-1 ansible_ssh_host=192.168.123.120 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-1 ansible_ssh_user=centos
rhhi-node-master-0 ansible_ssh_host=192.168.123.140 ansible_ssh_common_args="-o stricthostkeychecking=no" hostname=rhhi-node-master-0 ansible_ssh_user=centos
```
